### ISSUE TITLE
basic-illumination needs to properly account for complex folder structure of raw-images

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#101]
The current implementation infers the "experiment name" from the first token of the filename. https://github.com/labsyspharm/mcmicro-nf/blob/d647b4d82de2eb523698d2bb4fc02c737003c8e2/main.nf#L59-L63

This is potentially problematic for a complicated nested subfolder structure of .rcpnl files. The "experiment name" should account for the nested subfolder structure. Otherwise, there is a potential for a mismatched ordering of raw images and dfp/ffp files when these are provided to ASHLAR.

Jeremy suggested identifying the relative path between an image file and the `raw-images` folder and composing the "experiment name" by replacing "/" with "_" in this relative path. For example,
`TNP002-2D022520@20200307_033914_298197/TNP002-2D022520@20200307_033914_298197.rcpnl`
becomes
`TNP002-2D022520@20200307_033914_298197_TNP002-2D022520@20200307_033914_298197-ffp.tif`

This will ensure that sorting by filename on ffp/dfp files will match the sorting by full path on raw images.

**Comment by jmuhlich** [comment]
Implemented in #237. The "experiment name" is now generated from the first path component of the input file, which is the directory name for .xdce et al. and the filename itself for .rcpnl at al. This will cause everything to sort in the right order.
