### ISSUE TITLE
mcmicro all lower case?

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#105]
Do we all agree that mcmicro should be written lower case? If so, I will adapt readme and code.

**Comment by clarenceyapp** [comment]
i'm not particularly bothered either way

**Comment by ArtemSokolov** [comment]
Yes, all lowercase.

**Comment by ArtemSokolov** [comment]
`mcmicro` is spelled consistently in all-lowercase throughout the entire repository.
Please re-open this issue in repositories of individual modules, where this is still an issue.
