### ISSUE TITLE
Add documentation about using nextflow log to retrieve post-run information

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#114]
If a job finishes successfully it does not tell you the job name / file name. Would it be possible to include it into the slurm output?

**Comment by ArtemSokolov** [comment]
@DenisSch Can you clarify what filename you're talking about? Is this something specific to O2?

**Comment by DenisSch** [comment]
Yes, O2 specific.

Each run creates a slurm file with a unique (and random) number with the nextflow output. How can I connect the slurm file to the images that was run?

**Comment by DenisSch** [comment]
Example:
```
Checking labsyspharm/mcmicro-nf ...
Fast-forward - revision: 606a7d448b [master]
N E X T F L O W  ~  version 20.01.0
Launching `labsyspharm/mcmicro-nf` [grave_euler] - revision: 606a7d448b [master]

executor >  local (1), slurm (12)
[84/c34987] process > illumination   [100%] 8 of 8 ✔
[da/ba92b7] process > ashlar         [100%] 1 of 1 ✔
[-        ] process > dearray        -
[91/47ec01] process > unmicst        [100%] 1 of 1 ✔
[-        ] process > ilastik        -
[f4/1c2734] process > s3seg          [100%] 1 of 1 ✔
[06/ed74dd] process > quantification [100%] 1 of 1 ✔
[62/0c9f2a] process > provenance     [100%] 1 of 1 ✔
Completed at: 27-Apr-2020 22:15:40
Duration    : 5h 30m 57s
CPU hours   : 3.2
Succeeded   : 13
```

**Comment by DenisSch** [comment]
Can we add file name information here?

**Comment by ArtemSokolov** [comment]
TODO: Add documentation centered around the following commands:

`nextflow log`
`nextflow log -l`
`nextflow log last -f process,workdir`

**Comment by ArtemSokolov** [comment]
This is potentially made redundant by #133 which now saves all `.command.sh` and `.command.log` files into `qc/provenance` upon a successful pipeline run.

**Comment by DenisSch** [comment]
@ArtemSokolov Agree!
