### ISSUE TITLE
quantification: loop through multiple masks

### ISSUE THREAD

**Issue by clarenceyapp** [labsyspharm/mcmicro#121]
@DenisSch can there be a feature to accept multiple masks (ie. nucleiMask and cytoMask) and loop through the quantification? Sort of like the MeasureObjectIntensity module in Cellprofiler.

**Comment by ArtemSokolov** [comment]
We can loop through the masks in nextflow. This way they will be all processed in parallel. We just need to ensure that quantification accounts for it in the output filename, to avoid name collisions.

**Comment by clarenceyapp** [comment]
Following from some discussions with @ArtemSokolov and to give some context, Cellprofiler outputs a csv file for each mask (ie. nuclei, cytoplasm, or cell). The csv filenames can be appended with 'nuclei' and 'cytoplasm' in the same way that Cellprofiler does it to avoid collision and so that experimentalists know which region they're looking at. These regions can be inferred straight from the mask file names which are nucleiMask, cytoplasmMask, cellMask, etc. (or even eliminate 'Mask' for brevity).

**Comment by ArtemSokolov** [comment]
This needs to "play nicely" with the naming scheme being discussed in #97 .

**Comment by DenisSch** [comment]
This was now address with this new release:
https://github.com/labsyspharm/quantification/releases/tag/1.3.1

**Comment by ArtemSokolov** [comment]
@DenisSch What do you want the default `mcmicro` behavior to be? Pass all masks from `s3seg`?

Is this the correct usage?
`python CommandSingleCellExtraction.py --masks ./segmentation/cellMask.tif ./segmentation/membraneMask.tif ...`
(i.e., all mask files are passed to `--masks` a space-separated filenames).

**Comment by DenisSch** [comment]
@ArtemSokolov 
The first mask will be used for spatial features extraction (in your example `cellMask.tif`) and all additional masks will be only quantified without spatial information.
I would suggest to keep `cellMask.tif` default and if the user wants to add more masks they can be added as another parameter via mask name - something like

`--mask_spatial  cellMask.tif` --> which is default but can be changed
`--mask_add nucleiMask.tif cytoMask.tif` --> which can be added by the user

**Comment by ArtemSokolov** [comment]
To clarify, `--mask_spatial` and `--mask_add` are quantification parameters? or suggested mcmicro parameters?

**Comment by DenisSch** [comment]
Suggested mcmicro parameters. The quantification parameters did not change besides that we can add now more than one mask

**Comment by ArtemSokolov** [comment]
OK, this will require a little bit of work, since `mcmicro` needs to match up what `s3seg` writes out to what the user requests in `--mask_*`, and then to put the files in the correct order.

**Comment by DenisSch** [comment]
@ArtemSokolov Please let me know if I can help (or should try to implement it myself) or whether a change in the quantification module would be helpful.

**Comment by DenisSch** [comment]
It will also play well #97 - if we specify mask location via method and mask name
