### ISSUE TITLE
How to use "-resume" when running jobs as batch 

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#122]
@hywu0110 pointed out that "-resume" fails when using batch processing. It works when running jobs one by one or when referring to a specific run name:
<img width="769" alt="Screen Shot 2020-05-04 at 10 44 53 AM" src="https://user-images.githubusercontent.com/7010437/80979831-d6e42000-8df5-11ea-99c3-8070f2061157.png">
We should describe the use of -resume in a little more detail.

**Comment by ArtemSokolov** [comment]
@DenisSch and @hungyiwu : Can you please take a look at the `-resume` example in https://labsyspharm.github.io/mcmicro/#handling-intermediate-files and let me know what else you would like to add?

**Comment by hungyiwu** [comment]
Looks good to me, thank you!

**Comment by DenisSch** [comment]
Looks great - can be closed!
