### ISSUE TITLE
Consolidating UnMicst and ilastik output file styles

### ISSUE THREAD

**Issue by clarenceyapp** [labsyspharm/mcmicro#125]
This is for @clarenceyapp 's memory and for anyone else interested. UnMicst outputs separate probability map files whereas ilastik saves one tiff stack with each PM saved as a channel. It's easier to change UnMicst so that it behaves similar to ilastik. That way, S3segmenter doesn't even need to know where the maps are coming from. Nextflow will need to be updated as well to reflect this change in directing files. @ArtemSokolov , I will let you know when this is ready to be looked at. 

The only downside of doing this is that all maps now need to be written out regardless of whether they're being used or not, which increases computation time and space.

**Comment by ArtemSokolov** [comment]
Addressed in #157
