### ISSUE TITLE
Nextflow file locking issue

### ISSUE THREAD

**Issue by hungyiwu** [labsyspharm/mcmicro#127]
I got the error message below by running multiple instances of the pipeline in the same folder simultaneously

```
Checking labsyspharm/mcmicro-nf ...
Already-up-to-date - revision: 84d2bbab82 [master]
Can't lock file: /n/scratch2/hw233/workspace_z170/mcmicro/.nextflow/history -- Nextflow needs to run in a file system that supports file locks
```

I haven't dig into Nextflow's documentation or manual though.

**Comment by ArtemSokolov** [comment]
@hywu0110 Is this still an issue for you, after you started placing all files in `registration/`?

**Comment by hungyiwu** [comment]
It worked well when I put all files in `registration/`. Thank!
