### ISSUE TITLE
allow additional pre-stitched image file extensions

### ISSUE THREAD

**Issue by clarenceyapp** [labsyspharm/mcmicro#129]
can we allow the following file extensions as pre-stitched images in the registration folder to proceed through the pipeline, such as .btf, .nd2, and  .tif? These are straight from the microscope vendor's software (Nikon and Olympus).

**Comment by clarenceyapp** [comment]
and .czi too

**Comment by ArtemSokolov** [comment]
Can all three tools that use `registration/` (UnMicst, Coreograph and ilastik) read those formats?

**Comment by ArtemSokolov** [comment]
#133 added these here: https://github.com/labsyspharm/mcmicro-nf/blob/726e59c649876b41cda6a441072cb273d116c4ab/main.nf#L78-L82

The files still need to go through ASHLAR to be converted to `.ome.tif` to all downstream modules. Using ASHLAR as a converter in this way is easier than modifying Coreograph + UnMicst + ilastik to be able to work with all the requested formats.
