### ISSUE TITLE
Unfinished git merge causes issues [solution: reinstall nextflow]

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#131]
I am trying to run the pipeline starting with illumination and it crashes with the following error. I don't see a "HEAD" issue in the code

May-17 23:57:51.880 [main] DEBUG nextflow.cli.Launcher - $> nextflow run labsyspharm/mcmicro-nf --in /n/scratch2/ds230/MD3/Dev1_72/ -profile O2large -w /n/scratch2/ds230/work --start-at illumination
May-17 23:57:53.882 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.01.0
May-17 23:57:57.688 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.Exception: Project config file is malformed -- Cause: Compile failed for sources FixedSetSources[name='/groovy/script/Script42612E658142DD6A9B2D45852CA3E013/_nf_config_accda11f']. Cause: org.co$
/groovy/script/Script42612E658142DD6A9B2D45852CA3E013/_nf_config_accda11f: 41: unexpected token: << @ line 41, column 1.
   <<<<<<< HEAD
   ^

**Comment by ArtemSokolov** [comment]
That looks a artifact of an unfinished `git merge`. Line 41 in the config covers clusterOptions for illumination: https://github.com/labsyspharm/mcmicro-nf/blob/c86df44b61435e91e5015331c1d2465e51fc3eca/nextflow.config#L41

Did you by chance create a local version of the config, played around with various clusterOptions, then tried a 3-way `git merge` (or `git pull`) against the latest changes in the master?

**Comment by DenisSch** [comment]
@ArtemSokolov Is there a way to stash local changes?

**Comment by DenisSch** [comment]
@ArtemSokolov I get the error on o2 when using:
```./nextflow pull labsyspharm/mcmicro-nf```

**Comment by DenisSch** [comment]
@ArtemSokolov  I can not drop / remove the project:
```ds230@login06:~$ ./nextflow drop labsyspharm/mcmicro-nf
Project config file is malformed -- Cause: Compile failed for sources FixedSetSources[name='/groovy/script/Script42612E658142DD6A9B2D45852CA3E013/_nf_config_accda11f']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/groovy/script/Script42612E658142DD6A9B2D45852CA3E013/_nf_config_accda11f: 41: unexpected token: << @ line 41, column 1.
   <<<<<<< HEAD
   ^

1 error```

Have you seen this before?

**Comment by ArtemSokolov** [comment]
No, have not seen this before. Definitely looks like a conflict with `git`. Which directory are you running it from? Does it have a config file that is version-controlled by `git`?

Can you try doing `nextflow list` and `nextflow pull labsyspharm/mcmicro-nf` in a clean directory that doesn't have any other files?

**Comment by DenisSch** [comment]
Complete wipe and reinstallation was required to fix this issue.
