### ISSUE TITLE
Explicitly note which MATLAB version is required

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#14]
Error executing process > 'dearray (1)'

Caused by:
  Missing output file(s) `**{[A-Z],[A-Z][A-Z]}{[0-9],[0-9][0-9]}.tif` expected by process `dearray (1)`

Command executed:

  matlab -nodesktop -nosplash -r     "addpath(genpath('/Users/denis/mcmicro/Coreograph'));      tmaDearray('./stitched.ome.tif','outputPath','.','useGrid','true'); exit"

Command exit status:
  0

Command output:
  When constructing an instance of class
  'classreg.learning.classif.CompactClassificationTree', the constructor must
  preserve the class of the returned object.
  > In tmaDearray at 48
  Warning: While loading an object of class
  'classreg.learning.classif.CompactClassificationTree':
  When constructing an instance of class
  'classreg.learning.classif.CompactClassificationTree', the constructor must
  preserve the class of the returned object.
  > In tmaDearray at 48
  Warning: While loading an object of class
  'classreg.learning.classif.CompactClassificationTree':
  When constructing an instance of class
  'classreg.learning.classif.CompactClassificationTree', the constructor must
  preserve the class of the returned object.
  > In tmaDearray at 48
  Warning: While loading an object of class
  'classreg.learning.classif.CompactClassificationTree':
  When constructing an instance of class
  'classreg.learning.classif.CompactClassificationTree', the constructor must
  preserve the class of the returned object.
  > In tmaDearray at 48
  Warning: While loading an object of class
  'classreg.learning.classif.CompactClassificationTree':
  When constructing an instance of class
  'classreg.learning.classif.CompactClassificationTree', the constructor must
  preserve the class of the returned object.
  > In tmaDearray at 48
  Warning: While loading an object of class
  'classreg.learning.classif.CompactClassificationTree':
  When constructing an instance of class
  'classreg.learning.classif.CompactClassificationTree', the constructor must
  preserve the class of the returned object.
  > In tmaDearray at 48
  Warning: While loading an object of class
  'classreg.learning.classif.CompactClassificationTree':
  When constructing an instance of class
  'classreg.learning.classif.CompactClassificationTree', the constructor must
  preserve the class of the returned object.
  > In tmaDearray at 48
  Warning: While loading an object of class
  'classreg.learning.classif.CompactClassificationTree':
  When constructing an instance of class
  'classreg.learning.classif.CompactClassificationTree', the constructor must
  preserve the class of the returned object.
  > In tmaDearray at 48
  Warning: While loading an object of class 'TreeBagger':
  When constructing an instance of class 'TreeBagger', the constructor must
  preserve the class of the returned object.
  > In tmaDearray at 48

Command error:
  log4j:WARN No appenders could be found for logger (loci.formats.ClassList).
  log4j:WARN Please initialize the log4j system properly.
  Undefined function 'contains' for input arguments of type 'char'.

  Error in tmaDearray (line 52)
  if contains(fileName,'ome.tif')

Work dir:
  /Users/denis/work/38/db8ee6e2187138b5418ddb00e0c640

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by DenisSch** [comment]
Old MATLAB version creates this issue. We should add a check for that.

**Comment by ArtemSokolov** [comment]
Potential alternative is to port Coreograph to Python, thus removing MATLAB as a dependency altogether.
