### ISSUE TITLE
Clarify in the docs that Illumination Correction does not get run by default

### ISSUE THREAD

**Issue by edn314** [labsyspharm/mcmicro#140]
It is better to make this the default step before the registration step.

**Comment by DenisSch** [comment]
To give a little bit context:
When used only with `-stop-at` we should include illumination as a necessary step. Skipping it should be an option!

**Comment by jmuhlich** [comment]
I'm not confident enough in the illumination correction to run it by default, since I've seen it produce horrendous artifacts for small samples. The documentation should probably include more about each of the modules, including caveats for use and how to do QC on their output.

**Comment by ArtemSokolov** [comment]
@DenisSch Can you clarify what you mean?

Are you asking that, when the user specifies `--stop-at illumination`, the pipeline automatically adjusts `--start-at` to be illumination as well. (Thus reducing the need to explicitly specify `--start-at illumination`)

**Comment by DenisSch** [comment]
When using `stop-at registration` users assume that illumination is used. Edward is not the first person surprised that this is not the default step.
If you think illumination is not a default step, then we can keep it the way it is now...

**Comment by ArtemSokolov** [comment]
I see.

I agree with Jeremy that we need better documentation describing each module and when it should be run / gets run by the pipeline. (Related to #90)
