### ISSUE TITLE
Add a parameter for user to specify file suffix in the /raw directory

### ISSUE THREAD

**Issue by Yu-AnChen** [labsyspharm/mcmicro#149]
[Each microscope vendor has different file formats and structures](https://docs.openmicroscopy.org/bio-formats/5.8.2/formats/dataset-table.html), the current implementation tries to search for files with a set of pre-defined suffixes which covers most of the use cases. However, exposing a parameter that allows the user to specify the file suffix and overwrite the file search for their files would be useful for accommodating rare cases. One possibility is, e.g., `--raw-data-suffix .rcpnl`

**Comment by ArtemSokolov** [comment]
Note to self: the new parameter should override the default behavior in https://github.com/labsyspharm/mcmicro-nf/blob/f37b003d18640709b68c12063dcc55afdc0273f0/main.nf#L83-L87

**Comment by ArtemSokolov** [comment]
@Yu-AnChen : Would you be opposed to `--raw-formats`?

I was thinking of letting users specify multiple formats as it's done currently:
`--raw-formats '{.rcpnl,.ome.tif}'`

**Comment by Yu-AnChen** [comment]
@ArtemSokolov Sounds good to me, I think it's useful!
