### ISSUE TITLE
Minor inconsistencies in docs

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#159]
1. Example submit_mcmicro.sh: `/home/$USER/bin/nextflow labsyspharm/mcmicro` is missing the `run` verb.
2. Handling intermediate files needs a better example for `-resume`, since we're about to remove the last dependency on MATLAB.
3. Instructions for developers: step 3 is not needed, since the testing is now done automatically.

**Comment by DenisSch** [comment]
4. Add java download link for Nextflow installation

**Comment by ArtemSokolov** [comment]
5. Consider dropping `srun` from the O2 execution instructions. It prevents users from closing the shell / terminating their O2 session. Since most real datasets will take hours to run, `sbatch` is the preferred approach.

**Comment by mauliknariya** [comment]
6. In our example sbatch file, we have:
```
#!/bin/sh
#SBATCH -p medium
#SBATCH -J nextflow_O2              
#SBATCH -o run.o
#SBATCH -e run.e
#SBATCH -t 0-12:00
#SBATCH --mem=8G
#SBATCH --mail-type=END         # Type of email notification- BEGIN,END,FAIL,ALL
#SBATCH --mail-user=user@university.edu   # Email to which notifications will be sent
module purge
module load java matlab conda2
/home/$USER/bin/nextflow labsyspharm/mcmicro --in /n/scratch3/users/.../$USER/exemplar-001 -profile O2 -w /n/scratch3/users/.../$USER/work
```
I  think `#SBATCH -p` should be `short`  or `-t` should be longer. I don’t think `short` and `0-12:00` work.

**Comment by ArtemSokolov** [comment]
7. Directory structure section: "Subdirectories `illumination/` through `quantification/` have direct correspondence to the pipeline steps." -> "Subdirectories `illumination/` through `cell-states/` have direct correspondence to the pipeline steps."

**Comment by ArtemSokolov** [comment]
8. Using YAML parameter files section, "Anything that would appear as –flag on the command": `-flag` is missing backquotes.

**Comment by DenisSch** [comment]
The link for java example for MacOS:
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10/OpenJDK11U-jre_x64_mac_hotspot_11.0.7_10.pkg
