### ISSUE TITLE
Add cool travis icon/badge for travis

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#160]
Can we add the travis icon/badge to show that the build was successful. What else can / should we test with Travis? Can we run exemplar-001 fully and check the results?

**Comment by ArtemSokolov** [comment]
When we remove the MATLAB dependency, Travis CI can also be used to test exemplar-002.

"Checking" the results will probably be best done with those QC modules that you, Greg and everybody else are writing. When the QC modules are ready, we can configure Travis CI to fail a test if any particular QC metric doesn't pass a certain threshold.
