### ISSUE TITLE
xdce files compatibility

### ISSUE THREAD

**Issue by clarenceyapp** [labsyspharm/mcmicro#161]
xdce files and corresponding tiff files are not being handled correctly in mcmicro. Nextflow is treating each tiff file separately and sending them to BaSiC, ashlar, and so on for example, instead of treating the tiff files as a  'set' managed by the xdce master file.

**Comment by DenisSch** [comment]
@jmuhlich Is this something that requires a new module or can we include this into ASHLAR?

**Comment by clarenceyapp** [comment]
@jmuhlich this is being revisited because of a conversation that Denis and I had last week. I have a user who is using the INCell and wants to stitch and segment whole slides. Right now, they (and I) are running Ashlar separately and then feeding it back into mcmicro and starting from unmicst, which is abit inconvenient.
Also, I learnt recently that Russ Jenkins intends to do plate based CyCIF on our INCell within the next 3 weeks. Similar procedure to Caitlin's awhile back. Registration is required and they intend to use mcmicro if possible, but I don't think we're there yet.
So that's at least 2 use cases here to bring to your attention.

**Comment by ArtemSokolov** [comment]
Might need to poke him on Slack; he may have GitHub notifications disabled.

**Comment by jmuhlich** [comment]
Ashlar always supported xdce, but we need a new mcmicro module to enumerate
all the individual files for nextflow. That’s on me and I’ve been slow to
develop it.

**Comment by DenisSch** [comment]
@jmuhlich We have more and more users who need xdci file support in mcmicro. Is there something I can do to help here or is this already work in progress?

**Comment by jmuhlich** [comment]
I'm going to work on it this week.

**Comment by jmuhlich** [comment]
Implemented in #237.
