### ISSUE TITLE
O2TMAlarge hits time limit

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#163]
Users report ASHLAR getting terminated with the following

`slurmstepd: error: *** JOB 13055114 ON compute-h-17-51 CANCELLED AT 2020-07-11T22:48:26 DUE TO TIME LIMIT ***`

when using `-profile O2TMAlarge`. Should we bump the time limits to 12hrs for all processes to match the settings in `O2large` and `O2massive`?

**Comment by DenisSch** [comment]
Yes!

**Comment by ArtemSokolov** [comment]
Addressed in #164
