### ISSUE TITLE
UnMicst: allow running on GPU partition for large images

### ISSUE THREAD

**Issue by clarenceyapp** [labsyspharm/mcmicro#172]
some files are so large (X - Y) that they time out after 12 hours. Consider running on GPU partition if a conda environment can be made that is compatible on both the short and gpu partitions.

**Comment by clarenceyapp** [comment]
i created a new conda environment based on the dependencies that i have locally. This environment is incompatible with O2's short partition. It complains that a CUDA library file is missing when import tensorflow as tf is called. A quick search suggests that the wrong dependencies are being used and that tensorflow-gpu should default to using CPU if a GPU isn't present.

**Comment by clarenceyapp** [comment]
I built a new tensorflow-gpu environment on a compute node. This environment is able to run exemplar-001 and 002 even though it's on the short partition. Next test is to run this on the gpu partition

**Comment by clarenceyapp** [comment]
The following commands were used to build the environment:
conda create -n tf_gpu tensorflow-gpu cudatoolkit=9.0
conda install pillow
conda install nd2reader
conda install czifile=2019.7.2
conda install scikitimage=0.14.2

Interestingly, no cuDNN libraries are needed so far.

**Comment by clarenceyapp** [comment]
The tensorflow-gpu environment does not work on the GPU partition. Tensorflow can't find the M40 GPU using tf.test.is_gpu_available()

Rebuilt tensorflow-gpu environment on GPU partition. Automatically installs tensorflow 2.2 and CUDAtoolkit 10.0. Is able to detect M40 GPU.

NOTE:
CUDA 10 is backwards compatible, so this should work.
Tensorflow 2.2 is not compatible with UnMicst code. Trying Tensorflow 1.14.0 but job gets killed. Possibly because Tesla M40 is not compatible it.

**Comment by clarenceyapp** [comment]
It's possible to have tensorflow 2.2 installed but have it function as tensorflow 1 using:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Using this, tensorflow 2.2 conda environment works on the GPU partition (finds Tesla M40) and defaults to CPU on the short partition (reports CPU clock speed). Therefore, one conda environment seems to be sufficient. 

The only problem is that some libraries are no longer working including scikit-image and partition of image. I can downgrade python 3.8 to 3.6 but cannot downgrade skimage from 0.17 to 0.14. With skimage 0.14, tensorflow-base works.

**Comment by clarenceyapp** [comment]
RE: above issue with libraries not working and UnMicst getting killed is because the default amount of system memory requested on GPU partitions is quite low. After increasing to 16GB, both exemplars are working on both GPU and short partitions using the same conda environment.

**GPU found:**
2020-07-30 00:26:22.719570: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:03:00.0 name: Tesla M40 computeCapability: 5.2
coreClock: 1.112GHz coreCount: 24 deviceMemorySize: 11.18GiB deviceMemoryBandwidth: 268.58GiB/s

**Only CPU found but still continuing:**
2020-07-30 00:26:30.813209: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2599805000 Hz
2020-07-30 00:26:30.813453: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56121d2caac0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:


NOTE:
FLOAT16 isn't working with newer versions of scikit image, especially resize function. Need to convert to 8 bit. 


Procedure to build conda environment:
Go on a GPU partition
conda create -n tf_gpu tensorflow-gpu <<<this should install tensorflow 2.2
conda install cudatoolkit  <<<this should install cuda 10
conda install pillow
conda install nd2reader
conda install czifile=2019.7.2
conda install scikitimage  <<<this should install scikit-image 0.17

**Comment by clarenceyapp** [comment]
Built a single conda environment in /n/.....mcmicro/conda/unmicst-gpu that runs on the GPU and short partitions. Successfully runs exemplar-001 and exemplar-002 as well as a real dataset (40k x 30k pixels) that would normally time out but completes in about 10 minutes on a GPU. 

I encountered one hiccup where the cuDNN libraries failed to initialize. As soon as I reran it, it worked multiple times thereafter. Hrmph. 

conda yaml file looks like this:
name: unmicst-gpu
dependencies:
  - cudatoolkit
  - python
  - tensorflow-gpu
  - cudnn
  - scikit-image
  - matplotlib
  - scipy
  - tifffile
  - czifile=2019.7.2
  - nd2reader=3.2.3


Also had to update unmicst.py to handle:
-tensorflow 1.14 >> tensorflow 2.2
-scikit-image 0.17.2 not handling float 16. The probability maps need to be converted to 8bit before resizing. But resizing converts it to float again. We then reconvert to 8bit before saving prob maps, which is inefficient.

**Comment by clarenceyapp** [comment]
If there are multiple GPUs on the same node, occasionally, UnMicst will select a GPU that is already in use because UnMicst is hardcoded to use the first GPU. This will flag an out of memory error. Use the repo below to automatically select the unallocated GPU. 

https://github.com/bamos/setGPU/blob/master/setGPU.py

**Comment by ArtemSokolov** [comment]
@clarenceyapp Should we consider this completed by #178?

**Comment by clarenceyapp** [comment]
Yes
