### ISSUE TITLE
The fake NO_MASK file is giving issues in AWS runs

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#179]
TMA cores are paired with their dearray masks to make downstream processing easier. Since whole-slide images have no dearray masks, the pipeline constructs a fake `NO_MASK` to fill the gap in the pairing: https://github.com/labsyspharm/mcmicro/blob/3fde79b78249db77871b79bb2800310cfac8b007/main.nf#L239-L245

As a result, nextflow creates a symlink called `NO_MASK` in the corresponding working directory. This symlink is broken, since there is no actual file called `NO_MASK`. Normally, this is not an issue, since the symlink doesn't actually get used by `s3seg` when it's called with `--crop noCrop`. However, other processes on AWS attempt to sync up input files with S3, which requires following the symlinks and resolving them, leading to "file does not exist" errors.

One possible solution is to remove the surrounding `file()` on line 245 and have the channel emit `(core file, string)` tuples instead of `(core file, mask file)`. However, this may create a discrepancy with the TMA processing and require additional branching in the `s3seg` module.

**Comment by clarenceyapp** [comment]
another option might be to move the process that generates the mask from Coreograph to S3SEGMENTER so that masks don't even need to be passed.

**Comment by ArtemSokolov** [comment]
@clarenceyapp That would simplify things substantially!
