### ISSUE TITLE
The channel suffix produced by UnMicst / ilastik for s3seg should be 0-based

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#183]
s3seg assumes that a numeric `_n` suffix on probability map files should be interpreted as the `--probMapChan` argument. However, there is an off-by-one discrepancy between the suffix (which follows 1-based indexing) and the `probMapChan` argument (which assumes 0-based indexing).

Both UnMicst and ilastik should change their suffix output to be 0-based, to be consistent with 0-based indexing of channels assumed by all modules.

**This likely means that the built-in `.ilp` models in mcilastik need to be changed as well.**

**Comment by DenisSch** [comment]
@ArtemSokolov @clarenceyapp I will not include `_n` suffix into the `.ilp` output

**Comment by clarenceyapp** [comment]
@ArtemSokolov @DenisSch s3segmenter will soon be 0-based and not require _n suffix from ilastik. But it will need the user to specify a channel input using --probMapChan

**Comment by clarenceyapp** [comment]
This has been resolved right? S3segmenter will infer the channel number of expect user input

**Comment by ArtemSokolov** [comment]
There is still a discrepancy:
```
~/data/exemplar-002$ ls probability-maps/*
probability-maps/ilastik:
1_Probabilities_1.tif  2_Probabilities_1.tif  3_Probabilities_1.tif  4_Probabilities_1.tif

probability-maps/unmicst:
1_Probabilities_0.tif  2_Probabilities_0.tif  3_Probabilities_0.tif  4_Probabilities_0.tif
```

But I don't know if it has any impact. Does s3seg ignore the suffix now?

**Comment by clarenceyapp** [comment]
So previously, people would have to add a suffix to the ilastik prob maps. If people forgot, they'd be screwed. But now, s3segmenter just ignores if it's missing but requires it as an input argument under `--probMapChan`

**Comment by ArtemSokolov** [comment]
So, I think the outstanding action item is to remove the suffix from https://github.com/labsyspharm/mcmicro-ilastik/blob/master/classifiers/exemplar_001_nuclei.ilp which is what gets used when users don't provide their own ilastik model.

Once @DenisSch does this, we can close this issue.

**Comment by DenisSch** [comment]
So you want me to remove the "_1" from the ilastik classifier output?

**Comment by DenisSch** [comment]
Can't we make it backwards compatible? I have a few classifiers that are build that way...

**Comment by ArtemSokolov** [comment]
@DenisSch It *is* backwards compatible, but it's 0-based now. So, when ilastik uses `_1` as the suffix, s3seg will use the second channel. Here is the discrepancy on exemplar-002:

```
probability-maps/ilastik:
1_Probabilities_1.tif  2_Probabilities_1.tif  3_Probabilities_1.tif  4_Probabilities_1.tif

probability-maps/unmicst:
1_Probabilities_0.tif  2_Probabilities_0.tif  3_Probabilities_0.tif  4_Probabilities_0.tif
```

**Comment by DenisSch** [comment]
Sorry, I replied via email and have not seen the full thread. I will remove the suffix than...

**Comment by clarenceyapp** [comment]
@DenisSch i think Artem means that you can leave the suffix but it has to start from 0 because Python.

**Comment by DenisSch** [comment]
@clarenceyapp Sure, but if I already have to change it I can just remove it.

**Comment by ArtemSokolov** [comment]
@DenisSch just doesn't want to have to do it again when we inevitably go to -1-based indexing.

**Comment by DenisSch** [comment]
I have replaced the classifier: https://github.com/labsyspharm/mcmicro-ilastik/commit/902bb6d83d825f4f295ca2c7efedff36e68ff0ce
