### ISSUE TITLE
unmicst: replace unmicst v1 with unmicst v3 

### ISSUE THREAD

**Issue by clarenceyapp** [labsyspharm/mcmicro#196]
v3 is basically v1 (single channel on DAPI)  but with better training data, deeper network, more generalization, more tissue types

**Comment by DenisSch** [comment]
@clarenceyapp There is no situation where v1 will perform better? What about speed?

**Comment by clarenceyapp** [comment]
v1 was faster to train but that's already been done. V1 will not go away but people should try V3 instead as it is trained on more tissue types (v1 works terribly on exemplar-001)

**Comment by DenisSch** [comment]
Should we close this?

**Comment by clarenceyapp** [comment]
no
