### ISSUE TITLE
unmicst: allow user to run just one unmicst version instead of both

### ISSUE THREAD

**Issue by clarenceyapp** [labsyspharm/mcmicro#197]
based on user feedback, most people will only use one version or the other. Not both.

**Comment by ArtemSokolov** [comment]
In that case, would it make sense to add a wrapper to the UnMicst repo that forwards the call to either `UnMicst.py` or `UnMicst2.py` based on command line arguments? Then mcmicro would have just a single UnMicst module and the user would switch between the model versions through `--unmicst-opts`.

For example, the user would call:

`nextflow run labsyspharm/mcmicro --unmicst-opts 'v1 --stackOutput'`

which mcmicro would translate to:

`python UnMicstWrapper.py exemplar-001.ome.tif v1 --stackOutput`

which then cause the wrapper to forward the call to:

`python UnMicst.py exemplar-001.ome.tif --stackOutput`

**Comment by ArtemSokolov** [comment]
For exampl
