### ISSUE TITLE
Improve naming in flowchart output

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#201]
When exporting flowcharts via `-with-dag flowchart.png` the parameter and variables names should be improved.

<img width="802" alt="Screen Shot 2020-09-07 at 4 35 58 PM" src="https://user-images.githubusercontent.com/7010437/92415712-419cc380-f128-11ea-9bb6-1b3270ecba58.png">

**Comment by ArtemSokolov** [comment]
Hi @DenisSch,

There was a huge overhaul of code in the DSL2 port (#200), and most of those variable names don't exist anymore.

Can you please re-run with the latest version of the code and let me know if you are still unhappy with the way the DAG looks?

**Comment by DenisSch** [comment]
It looks very similar, but I am not sure how much we can do make it much more comprehensive. I will try to play around in cytoscape.

**Comment by ArtemSokolov** [comment]
This is effectively superseded by the Galaxy diagrams. (See Fig 2A in the manuscript.)
