### ISSUE TITLE
Discussion - move the --mask-spatial and --mask-add to the quantification module --masks?

### ISSUE THREAD

**Issue by Yu-AnChen** [labsyspharm/mcmicro#202]
I was thinking about replacing the `--mask-spatial m1.tif` and `--mask-add m2.tif m3.tif` from mcmicro to `--quant-opts m1.tif m2.tif m3.tif`, after realizing the role the pipeline played - globbing matched files and staging files, I think it makes sense to keep the argument in mcmicro instead of in the quantification module. 

I'm not sure we should have both `--mask-spatial` and `--mask-add` or just using the first mask in `--mask-spatial` (`--quantification-masks` for better naming in this case) to quantify spatial properties. 

In the documentation, I'd find it more clear to have the `--mask-spatial` and `--mask-add` documented in the section of "Parameters controlling the pipeline behavior" > "Optional parameters:", since it's more of pipeline behavior instead of parameters one would tweak running the individual module.

**Comment by ArtemSokolov** [comment]
Honestly, I can see benefits to both implementations, so I don't have a strong opinion. But I do want to point out that the nextflow code will simplify substantially if we move `--mask-spatial` + `--mask-add` to `--quant-opts`.

So I'm leaning slightly in favor of your suggestion, @Yu-AnChen.

**Comment by DenisSch** [comment]
@Yu-AnChen Sounds good to me.

**Comment by DenisSch** [comment]
Is there anything I should do on the quantification module?

**Comment by ArtemSokolov** [comment]
@DenisSch I don't think so. Should just be a change in the nextflow code.

**Comment by Yu-AnChen** [comment]
Thank you guys! Sounds like we should wait for the specs from Jeremy before getting to this :)
