### ISSUE TITLE
Try out the just-the-docs jekyll theme for mcmicro documentation?

### ISSUE THREAD

**Issue by Yu-AnChen** [labsyspharm/mcmicro#203]
[just-the-docs](https://github.com/pmarsceill/just-the-docs) seems to have some nice features for using jekyll for documentation, shall we try it out?

**Comment by ArtemSokolov** [comment]
I think it looks great! Do you want to work on a pull request that incorporates this, Yu-An?

**Comment by Yu-AnChen** [comment]
Sounds good, I'll try it out and share!

**Comment by Yu-AnChen** [comment]
I've built [a demo on my fork](https://yu-anchen.github.io/mcmicro/) for us to review, please check it out when you have time 🙂

**Comment by ArtemSokolov** [comment]
That looks fantastic, @Yu-AnChen.

**Comment by Yu-AnChen** [comment]
Thank you! I'll clean it up a bit and submit the PR, note the file structure will be [a bit more complicated](https://github.com/Yu-AnChen/mcmicro/tree/PR-use-just-the-doc-theme/docs) than what we have now, hopefully it's still easy enough!

**Comment by clarenceyapp** [comment]
Very nice, @Yu-AnChen ! I just sent the old instructions to someone just starting. I will send your once it's done. I think having a schematic diagram that shows the order of each step of the pipeline is necessary for people without any analytical background.

**Comment by ArtemSokolov** [comment]
@Yu-AnChen I think that's OK. It looks like people will still be able to edit individual `.md` files without worrying about how they get compiled together.

**Comment by DenisSch** [comment]
@Yu-AnChen Looks awesome! Thank you!

**Comment by ArtemSokolov** [comment]
Addressed in #206
