### ISSUE TITLE
Contributors page

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#207]
Consider adding a contributors page on https://labsyspharm.github.io/mcmicro/ that lists individuals who made significant contributions to the development or testing of mcmicro and its modules.

(Generate a draft based on the Acknowledgments slide in a recent presentation.)

**Comment by DenisSch** [comment]
Good idea and we could also add like a "Code of conduct"

**Comment by DenisSch** [comment]
I am taking care of this part and also adding CODE OF CONDUCT (copied from napari)

**Comment by ArtemSokolov** [comment]
Reminder: redo the funding. (Remove the two U2C grants, add Denis's fellowship.)

**Comment by DenisSch** [comment]
I have added the discussed point: https://github.com/labsyspharm/mcmicro/tree/DenisSch-CODEOFCONDUCT

We just need to make sure it fits well with the docs and readme on the Github page

**Comment by ArtemSokolov** [comment]
I think the full list of contributors and CoC should be standalone pages in the docs. But the README can link out to them (e.g., as done here: https://github.com/tidyverse/tidyverse#code-of-conduct)

Let's not forget to include Yu-An and Juha (https://github.com/labsyspharm/mcmicro/graphs/contributors)
We should have a separate section for all of our power users / beta testers.

**Comment by DenisSch** [comment]
Absolutely! I am restructuring the readme + documentation and I will share soon
