### ISSUE TITLE
Initialize the default value of `--ilastikModel` to be interpretable as `exemplar_001_nuclei.ilp`

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#211]
https://github.com/labsyspharm/mcmicro/blob/7547d0c42a7851eb2f9b36dd020660a9159e6ae1/modules/probability-maps.nf#L39

@ArtemSokolov Can we rename "NO_MODEL" to the actual model name?

**Comment by ArtemSokolov** [comment]
That's what lines 39-40 do.....

https://github.com/labsyspharm/mcmicro/blob/7547d0c42a7851eb2f9b36dd020660a9159e6ae1/modules/probability-maps.nf#L39-L40

It says:
-if a user supplied a model through `--ilastikModel`, then use that model, which was staged as `input.ilp` in line 28.
-if a user didn't supply a model (which is marked internally as "NO_MODEL"), then use "/app/classifiers/exemplar_001_nuclei.ilp" as the default.

**Comment by DenisSch** [comment]
Correct. What I am really saying: It would nice to see `exemplar_001_nuclei.ilp` in the `params.yml` instead of "NO_MODEL" :)

**Comment by ArtemSokolov** [comment]
Note to self: additional care must be taken, so that mcmicro doesn't attempt to look for `exemplar_001_nuclei.ilp` in the local compute environment, since the file exists inside the ilastik container only.

Relevant portion of the code:
https://github.com/labsyspharm/mcmicro/blob/7547d0c42a7851eb2f9b36dd020660a9159e6ae1/main.nf#L84-L85

**Comment by ArtemSokolov** [comment]
I decided to replace `'NO_MODEL'` with `'built-in'`. This will help avoid any potential filename conflicts (imagine if a user creates their own `exemplar_001_nuclei.ilp` that they want to pass to mcmicro), and the user doesn't really need to know what the built-in model is named anyway.

The change is incorporated into the pull request mentioned above.
