### ISSUE TITLE
Redesign project directory structure to make it easier to avoid archiving copies of primary image data

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/mcmicro#227]
I've noticed that people tend to archive their entire mcmicro project directory on durable storage after completing the pipeline run. This includes the `raw/` subdirectory containing primary image data. If primary data is retained elsewhere, this results in a duplication of these very large files. I propose we redesign the directory structure to keep input/primary data more separated from pipeline output files so users can easily archive just the outputs.

**Comment by clarenceyapp** [comment]
_fiiiiiiiiiiine_

**Comment by ArtemSokolov** [comment]
In my opinion, a better solution is to allow users to specify a data source that is "external" to the project directory, i.e., something like:

```
nextflow run labsyspharm/mcmicro --in /path/to/myproject --data /path/to/somedataset
```

where `--data` defaults to `/path/to/myproject/raw` if not specified.

This would be a minimally invasive change limited to https://github.com/labsyspharm/mcmicro/blob/2189707e28316e600e53aff7b46af8234bbb5d59/main.nf#L75-L77

**Comment by ArtemSokolov** [comment]
It appears that the issue is easily addressable with a symbolic link. For example,

```
$ tree test/
test/
├── markers.csv
└── raw -> /data/exemplar-001/raw/
```

contains a symbolic link `raw/` pointing to where the original (potentially very large) images reside.

Executing `nextflow run labsyspharm/mcmicro --in ./test` will properly resolve the symbolic link, and the files get correctly staged to point to the original source of data:

```
$ ls -l work/ea/c2fda2b2916bd33acd90ac4a29bfcc/
...
lrwxrwxrwx 1 sokolov sokolov        53 Aug 16 14:06 exemplar-001-cycle-01.ome.tiff -> /data/exemplar-001/raw/exemplar-001-cycle-01.ome.tiff
lrwxrwxrwx 1 sokolov sokolov        53 Aug 16 14:06 exemplar-001-cycle-02.ome.tiff -> /data/exemplar-001/raw/exemplar-001-cycle-02.ome.tiff
lrwxrwxrwx 1 sokolov sokolov        53 Aug 16 14:06 exemplar-001-cycle-03.ome.tiff -> /data/exemplar-001/raw/exemplar-001-cycle-03.ome.tiff
```
