### ISSUE TITLE
Transition to using `--unmicst-opts '--tool 1.5'` as the default

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#243]
Currently, UnMicst defaults to `--tool 1`, which has been effectively deprecated by v1.5.

Begin the transition to the `--tool 1.5` default. Use warning / error messages to ensure that workflows that currently rely on v1 understand that 1.5 will be the new default.

**Comment by clarenceyapp** [comment]
@ArtemSokolov while doing this, it turns out that there are ALOT of other warning messages that Tensorflow displays. A warning message about v1 deprecation is going to get lost and go unnoticed.

**Comment by ArtemSokolov** [comment]
Is there a way to suppress tensorflow verbiage? I feel that it already makes it difficult to see module messages and meaningful error messages.

**Comment by clarenceyapp** [comment]
@ArtemSokolov 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' is reported to only show fatal error messages.

Anyway, the current version of unmicst now uses v1.5 as default and prints appropriate warning messages when v1 or v1.5 are used. This does not ensure that people will open the logs and read them though.

**Comment by clarenceyapp** [comment]
@ArtemSokolov so actually, this works:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import logging
logging.getLogger('tensorflow').setLevel(logging.FATAL)

**Comment by clarenceyapp** [comment]
@ArtemSokolov I set the log level to '2' now so that errors are also printed just in case. In a clean run, there are no messages. Level '1' would be info and adds one extra warning message.

There are a couple of custom messages that I've left.

**Comment by clarenceyapp** [comment]
@ArtemSokolov I think this issue has been resolved now.

**Comment by ArtemSokolov** [comment]
Ok.
