### ISSUE TITLE
Store TMA centroids

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#268]
The new version of Coreograph will produce `centroids.txt`. Have mcmicro store it to `qc/coreo`.

Add appropriate lines to: https://github.com/labsyspharm/mcmicro/blob/38b0a8536b71ae03b001c95e03985ddbcee81771/modules/dearray.nf#L5-L6

and
https://github.com/labsyspharm/mcmicro/blob/38b0a8536b71ae03b001c95e03985ddbcee81771/modules/dearray.nf#L16-L20

**Comment by clarenceyapp** [comment]
just submitted a PR. The filename will actually be centroidsY-X.txt

**Comment by ArtemSokolov** [comment]
Addressed in #269
