### ISSUE TITLE
Channel name CSV missing

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#27]
We don't have any information about the channel names

**Comment by ArtemSokolov** [comment]
We have channel names for the exemplars. None of the tools explicitly required them so far, so I never bothered pulling them from S3.

I can update exemplar.nf to pull them, if you need them for your tools.

**Comment by DenisSch** [comment]
Yes I need them for quantification! Thank you!

**Comment by ArtemSokolov** [comment]
OK, I'll prioritize this when I work on the pipeline next.

In the meantime, here are S3 links:
Exemplar-001: https://mcmicro.s3.amazonaws.com/exemplars/001/exemplar-001/markers.csv
Exemplar-002: https://mcmicro.s3.amazonaws.com/exemplars/002/exemplar-002/markers.csv
