### ISSUE TITLE
Running on O2 outside lsp group

### ISSUE THREAD

**Issue by keller-mark** [labsyspharm/mcmicro#272]
Hi,
I see in the documentation that mcmicro requires O2 accounts to be in the `lsp` group to have permissions to run the containers. Is it possible to relax this constraint?

I am currently trying to run the `exemplar-001` example (with config file [here](https://github.com/keller-mark/saberfish-mcmicro/blob/2b4ee3def5365f916feb807c0a339e00f185da94/mk596.config)) but I run into this: `singularity image is not in an allowed configured path`

<img width="1742" alt="Screen Shot 2021-04-09 at 1 27 33 PM" src="https://user-images.githubusercontent.com/7525285/114219188-56e50500-9938-11eb-83b2-23a1fb0c8c9d.png">

I see that there is a way to submit singularity images for [automated testing](https://wiki.rc.hms.harvard.edu/display/O2/Running+Singularity+Containers+in+O2)  which I tried but did not seem to work due to the `.img` extension

```sh
[mk596@compute-a-16-167 mk596]$ csubmitter --name saberfish-mcmicro-ashlar --image-path /n/scratch3/users/m/mk596/saberfish-mcmicro/singularity/labsyspharm-ashlar-1.13.0.img
File does not seem to be valid singularity file extension of .def, .simg or .sif
```

**Comment by keller-mark** [comment]
Sorry, never mind, I figured it out.

For any future HMS people: I just had to rename the local singularity image to have a `.sif` extension before submitting to `csubmitter`, then update my nextflow config to point to the verified singularity image in `/n/app/singularity/containers/$USER` with the `file:///` prefix https://www.nextflow.io/docs/latest/singularity.html#singularity-docker-hub

**Comment by ArtemSokolov** [comment]
Thanks, Mark. I'm going to reopen the issue, because I think your last post contains important information that we should include in our documentation.

**TODO**: Add relevant instructions to https://github.com/labsyspharm/mcmicro/blob/master/docs/run-O2.md#running-mcmicro-on-the-o2-compute-cluster

**Comment by keller-mark** [comment]
Ok great, I am adding some notes to the readme here in case they might be helpful https://github.com/keller-mark/saberfish-mcmicro#readme

**Comment by ArtemSokolov** [comment]
One possible alternative that may work is to overwrite https://github.com/labsyspharm/mcmicro/blob/c7b237fd9ae68bc70f323cc68218750f35a6f6cc/config/O2base.config#L3

Compose a `myproject.config` with
```
singularity.cacheDir  = '/n/app/singularity/containers/mk596'
```
alongside any [special resource requirements](https://mcmicro.org/run-O2.html#requesting-o2-resources). Then pass the custom config to the pipeline with `-c`:

```
nextflow run labsyspharm/mcmicro --in /path/to/exemplar-001 -profile O2 -c myproject.config
```

I haven't tested this yet, but in theory it should work, because `-c` overwrites whatever was specified in `-profile`.

**Comment by ArtemSokolov** [comment]
Hi @keller-mark,

I implemented a prototype solution based on this workaround: https://github.com/nextflow-io/nextflow/issues/1155#issuecomment-690799250

When you have a moment, can you please try running the following commands on O2, on a compute node with at least 8GB RAM?

```
# Download exemplar-001 as usual
nextflow run labsyspharm/mcmicro/exemplar.nf --name exemplar-001 --path .

# Create a .mcmicro directory in $HOME and fill it with symlinks to Singularity containers
nextflow run ArtemSokolov/mcmicro/setup/O2ext.nf -r o2ext

# Run the pipeline using the new symbolic links (profile O2ext)
nextflow run ArtemSokolov/mcmicro -r o2ext --in ./exemplar-001 -profile O2ext
```

The last two commands are using my developer fork (branch `o2ext`). Please me know if the exemplar runs to completion (should take approximately 15-20mins). I will then document this prototype and merge it into master.

To clean up, simply delete `$HOME/.mcmicro` afterwards.
