### ISSUE TITLE
Exemplar doesn't work with Nextflow 21

### ISSUE THREAD

**Issue by lambdamoses** [labsyspharm/mcmicro#277]
Hi, I was trying to run the examplar on your README page (`nextflow run labsyspharm/mcmicro --in exemplar-001`), and got this:

```
N E X T F L O W  ~  version 21.04.0
Launching `labsyspharm/mcmicro` [tiny_mayer] - revision: 85e8070c7a [master]
mcmicro requires Nextflow version 20.07 or greater
Run the following command to update: nextflow self-update
```

However, when I forced using Nextflow 20.07, with `NXF_VER=20.07.0 nextflow run labsyspharm/mcmicro --in exemplar-001`, it worked.

**Comment by ArtemSokolov** [comment]
Thanks, @lambdamoses 

Looks like the [nextflow example of using postfix notation](https://www.nextflow.io/docs/latest/metadata.html#nextflow-metadata) wasn't working here. Just submitted a pull request with the fix.

Will merge once it goes through the automated tests.
