### ISSUE TITLE
Add information about `nextflow clean` explaining how to remove temporary files

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#28]
Nextflow creates a lot of temporary files in the work directory, which need to be automatically deleted.

**Comment by ArtemSokolov** [comment]
I don't think temporary files should be removed automatically. They are essential for the `-resume` directive, which allows you to use cached results from successful module runs without rerunning the whole pipeline: https://www.nextflow.io/blog/2019/demystifying-nextflow-resume.html

Nextflow has a `clean` command that can be used to remove parts of the work directory in a robust fashion: https://github.com/nextflow-io/nextflow/blob/cli-docs/docs/cli.rst#clean

If you want to blow away the entire work directory, then a simple `rm -rf work` should do the trick. ;)

**Comment by DenisSch** [comment]
I accumulated about 30GB of data with just exemplar-001 running with different options. We should think about a way to delete the files if the pipeline finishes successfully.

**Comment by ArtemSokolov** [comment]
I still don't think it should be done automatically. The user may want to inspect the logs, even after a 100% successful run.

We can add information about `nextflow clean` to README. That way the user can remove the temporary files once they are fully done with them.

**Comment by DenisSch** [comment]
And add the information regarding ```-w path/to/work``` option
