### ISSUE TITLE
Error: images must be same size for register_translation

### ISSUE THREAD

**Issue by huanlity** [labsyspharm/mcmicro#288]
Hi I am using MCMICRO to process some codex data. Some of them failed in the registration step  due to the error message shown below. Anybody has seen this before? Any suggestion is greatly appreciated. Thanks!

Here is the error message:
`    reading Cycle5_channel_0.ome.tif
WARNING:(B Stage coordinates undefined; falling back to (0, 0).
    assembling thumbnail 1/1
    estimated cycle offset [y x] = [0. 0.]
    aligning tile 1/1Traceback (most recent call last):
  File "/usr/local/bin/ashlar", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/ashlar/scripts/ashlar.py", line 174, in main
    args.quiet
  File "/usr/local/lib/python3.7/dist-packages/ashlar/scripts/ashlar.py", line 229, in process_single
    layer_aligner.run()
  File "/usr/local/lib/python3.7/dist-packages/ashlar/reg.py", line 806, in run
    self.register_all()
  File "/usr/local/lib/python3.7/dist-packages/ashlar/reg.py", line 834, in register_all
    shift, error = self.register(i)
  File "/usr/local/lib/python3.7/dist-packages/ashlar/reg.py", line 893, in register
    shift, error = utils.register(ref_img, img, self.filter_sigma)
  File "/usr/local/lib/python3.7/dist-packages/ashlar/utils.py", line 32, in register
    img1_f, img2_f, upsample, 'fourier'
  File "/usr/local/lib/python3.7/dist-packages/skimage/feature/register_translation.py", line 160, in register_translation
    raise ValueError("Error: images must be same size for "
ValueError: Error: images must be same size for register_translation`

Here is my command in a jupyter notebook:
`cmd = f"docker run --rm -it --user root -v /home/whuan/store/{SAMPLE}/registration/:/data/ labsyspharm/ashlar /bin/sh -c \'cd /data/; ashlar Cycle0_channel_0.ome.tif Cycle0_channel_1.ome.tif Cycle0_channel_2.ome.tif Cycle0_channel_3.ome.tif Cycle1_channel_0.ome.tif Cycle1_channel_1.ome.tif Cycle1_channel_2.ome.tif Cycle1_channel_3.ome.tif Cycle2_channel_0.ome.tif Cycle2_channel_1.ome.tif Cycle2_channel_2.ome.tif Cycle2_channel_3.ome.tif Cycle3_channel_0.ome.tif Cycle3_channel_1.ome.tif Cycle3_channel_2.ome.tif Cycle3_channel_3.ome.tif Cycle4_channel_0.ome.tif Cycle4_channel_1.ome.tif Cycle4_channel_2.ome.tif Cycle4_channel_3.ome.tif Cycle5_channel_0.ome.tif Cycle5_channel_1.ome.tif Cycle5_channel_2.ome.tif Cycle5_channel_3.ome.tif Cycle6_channel_0.ome.tif Cycle6_channel_1.ome.tif Cycle6_channel_2.ome.tif Cycle6_channel_3.ome.tif Cycle7_channel_0.ome.tif Cycle7_channel_1.ome.tif Cycle7_channel_2.ome.tif Cycle7_channel_3.ome.tif Cycle8_channel_0.ome.tif Cycle8_channel_1.ome.tif Cycle8_channel_2.ome.tif Cycle8_channel_3.ome.tif Cycle9_channel_0.ome.tif Cycle9_channel_1.ome.tif Cycle9_channel_2.ome.tif Cycle9_channel_3.ome.tif --tile-size 512 --pyramid -f {SAMPLE}.ome.tif\'"
! {cmd}`

**Comment by huanlity** [comment]
I checked the stitched images and their dimension. All looks good to me.
![image_dimension](https://user-images.githubusercontent.com/26349803/122282588-92142f00-ceb9-11eb-877e-6972f3272d9b.png)
![image_sample](https://user-images.githubusercontent.com/26349803/122282597-96404c80-ceb9-11eb-8c62-87a204035900.png)

**Comment by huanlity** [comment]
@ArtemSokolov

**Comment by jmuhlich** [comment]
Based on your image dimensions of over 16000 pixels, it looks like you're trying to register images that have already been stitched. Ashlar is meant to be given the tiles for each cycle _before_ stitching, and it will perform coordinated stitching and registration. What microscope are you using, and what file format images does it produce prior to stitching?

**Comment by huanlity** [comment]
I can provide more information on the microscope later but it is called Dragonfly. The file format before stitching is .ims, so we have to convert the images to tif before Ashlar.

The pipeline I am using now was put together by a former colleague who left our organization already. He could not get the MCMICRO to run through all the steps within the NEXFLOW so steps before dearray were done outside of it, including:

- Converting data format from `ims` to `tiff` using 
- Stitching
- Registration

Stitching commands:
iCnt = 0
for cycle in allCycles:
    cmd = f"ashlar 'fileseries|raw/cycle{iCnt}|pattern=Cycle_{iCnt}_F{{series:3}}.tif|width={CON['Columns']}|height={CON['Rows']}|overlap=0.10|pixel_size=0.325|direction=vertical|layout=snake'\
    --flip-y --filter-sigma 1 --ffp illumination/cycle{iCnt}-ffp.tif --dfp illumination/cycle{iCnt}-dfp.tif -f registration/Cycle{iCnt}_channel_{{channel}}.ome.tif"
    print(cmd, '\n')
    ! {cmd}
    iCnt += 1 

registration command:
cmd = f"docker run --rm -it --user root -v /home/whuan/store/{SAMPLE}/registration/:/data/ labsyspharm/ashlar /bin/sh -c \'cd /data/; ashlar Cycle0_channel_0.ome.tif Cycle0_channel_1.ome.tif Cycle0_channel_2.ome.tif Cycle0_channel_3.ome.tif Cycle1_channel_0.ome.tif Cycle1_channel_1.ome.tif Cycle1_channel_2.ome.tif Cycle1_channel_3.ome.tif Cycle2_channel_0.ome.tif Cycle2_channel_1.ome.tif Cycle2_channel_2.ome.tif Cycle2_channel_3.ome.tif Cycle3_channel_0.ome.tif Cycle3_channel_1.ome.tif Cycle3_channel_2.ome.tif Cycle3_channel_3.ome.tif Cycle4_channel_0.ome.tif Cycle4_channel_1.ome.tif Cycle4_channel_2.ome.tif Cycle4_channel_3.ome.tif Cycle5_channel_0.ome.tif Cycle5_channel_1.ome.tif Cycle5_channel_2.ome.tif Cycle5_channel_3.ome.tif Cycle6_channel_0.ome.tif Cycle6_channel_1.ome.tif Cycle6_channel_2.ome.tif Cycle6_channel_3.ome.tif Cycle7_channel_0.ome.tif Cycle7_channel_1.ome.tif Cycle7_channel_2.ome.tif Cycle7_channel_3.ome.tif Cycle8_channel_0.ome.tif Cycle8_channel_1.ome.tif Cycle8_channel_2.ome.tif Cycle8_channel_3.ome.tif Cycle9_channel_0.ome.tif Cycle9_channel_1.ome.tif Cycle9_channel_2.ome.tif Cycle9_channel_3.ome.tif --tile-size 512 --pyramid -f {SAMPLE}.ome.tif\'"
! {cmd}

**Comment by ArtemSokolov** [comment]
@huanlity Can you try removing the outer loop `for cycle in allCycles` and just passing all tiles directly to ASHLAR to perform stitching and registration as a single step (which is what the tool was designed to do)?

**Comment by jmuhlich** [comment]
Yes, what Artem said. You can pass all 10 `fileseries` strings at once and include `--tile-size 512 --pyramid -f …`. You’ll need to keep `--flip-y --filter-sigma 1` in there, and also pass all 10 ffp and dfp image files to a single  --ffp and single  --dfp argument.

**Comment by huanlity** [comment]
@jmuhlich @ArtemSokolov  Thank you both! I am trying to feed 10 cycles of `fileseries` at once and having a hard time, could you please check this screenshot and see if I am doing it correctly? Thank you!
<img width="1510" alt="ashlar_cmd" src="https://user-images.githubusercontent.com/26349803/123970422-1d47f700-d987-11eb-95e8-788049e6ed26.png">

**Comment by huanlity** [comment]
I tried the command above and it worked for the most part. I could stitch and register all 40 channels (10 cycle by 4 channels/cycle) without problem but the building pyramid failed when processing level 2 data. Here is the error, do you guys have any idea? Thanks again!

<img width="1435" alt="pyramid_error" src="https://user-images.githubusercontent.com/26349803/123986122-08be2b80-d994-11eb-860e-4c1b94699feb.png">

**Comment by Yu-AnChen** [comment]
Sorry to hear that @huanlity, could you test one thing for us? Since you are using conda, please try install ashlar in a fresh conda environment, you can do so by running

```bash
conda create -y -n ashlar python=3.7
conda activate ashlar
conda install -y -c conda-forge numpy scipy matplotlib networkx scikit-image=0.16.2 scikit-learn pyjnius
pip install ashlar
```

then test one cycle first to see if the error still persist
```bash
ashlar "fileseries|raw/cycle0|pattern=Cycle_0_F{series:3}.tif|width=9|height=9|overlap=0.10|pixel_size=0.325|direction=vertical|layout=snake" --tile-size 512 --pyramid -f crc4-test.ome.tif
```

**Comment by jmuhlich** [comment]
Note that your `crc4.ome.tif` output file should be usable as a regular tiff file, even though Ashlar exited with an error. The pyramid levels and OME metadata won't be present, but the basic TIFF planes for your 40 channels should be there.

Could you please tell us the version of `tifffile` installed in your main anaconda environment (separate from Yu-An's suggestion of a fresh environment)?

**Comment by huanlity** [comment]
@jmuhlich  I was having a `tifffile==2020.10.1` and then I installed the latest version: `tifffile==2021.6.14` to give it a try. It failed at the exactly same spot.

**Comment by Yu-AnChen** [comment]
@huanlity If you'd prefer using your main conda env, uninstall tifffile first by running 

```
pip uninstall tifffile
```

Then your scikit-image will use the vendored version of tifffile. That may resolve it.

**Comment by huanlity** [comment]
@Yu-AnChen  I pip uninstalled tifffile and tried again, here is what I got. I don't know if it is actually using the scikit-image is using the vendored version of tifffile. Do you have any idea? I will also try in a fresh env.
<img width="1407" alt="tifffile_uninstalled" src="https://user-images.githubusercontent.com/26349803/124024009-a4fc2880-d9bc-11eb-9af2-45312f50823f.png">

**Comment by huanlity** [comment]
It also failed in the fresh ashlar conda env I just created:
![fresh_ashlar_env](https://user-images.githubusercontent.com/26349803/124024573-61ee8500-d9bd-11eb-8c22-cfcfb34b66c2.png)

**Comment by Yu-AnChen** [comment]
Sorry I missed that you were using `--flip-y --filter-sigma 1` in your previous run, could you add them back and try again? And please also check my hand-typed command is correct, I was looking at you screenshots.

**Comment by huanlity** [comment]
@Yu-AnChen No worries, the screenshots contains the command and both of them have the `--flip-y --filter-sigma 1` part. I also tried without it but it failed again.

**Comment by Yu-AnChen** [comment]
Thanks @huanlity for all the testing and my bad for missing that again  😓 

I think the "No tiles overlap" resulted in the later error, but it's unclear to me that you are seeing that only after switching to the vendored version of `tifffile`. Is it possible for you to share one tile of your data for me to look into? For example the `Cycle_0_F040.tif`?

**Comment by huanlity** [comment]
It looks like that github does support tiff file uploading. Do you mind sharing your email so I can send you the file? I really appreciate your help. At the same time, I am a bit suspect if the vendored version of `tifffile` was used at all…not sure how to check.

**Comment by huanlity** [comment]
@Yu-AnChen I just shared the file with your harvard medical school email. Please let me know if you cannot access it. Thanks!

**Comment by Yu-AnChen** [comment]
As for checking which `tifffile`, you can try to open a tiff file that does not exist

```python
import skimage.io                                                       
skimage.io.imread('does-not-exist.tif')  
```

by looking into the stack trace, you'd see that the vendored tifffile `/miniconda3/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py` was called                 

```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-433945fa683e> in <module>
----> 1 skimage.io.imread('does-not-exist.tif')

~/miniconda3/lib/python3.7/site-packages/skimage/io/_io.py in imread(fname, as_gray, plugin, **plugin_args)
     46 
     47     with file_or_url_context(fname) as fname:
---> 48         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     49 
     50     if not hasattr(img, 'ndim'):

~/miniconda3/lib/python3.7/site-packages/skimage/io/manage_plugins.py in call_plugin(kind, *args, **kwargs)
    208                                (plugin, kind))
    209 
--> 210     return func(*args, **kwargs)
    211 
    212 

~/miniconda3/lib/python3.7/site-packages/skimage/io/_plugins/tifffile_plugin.py in imread(fname, dtype, **kwargs)
     46 
     47     # read and return tiff as numpy array
---> 48     with TiffFile(fname, **kwargs_tiff) as tif:
     49         return tif.asarray(**kwargs)

~/miniconda3/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py in __init__(self, arg, name, offset, size, multifile, multifile_close, pages, fastij, is_ome)
   1328 
   1329         self._fh = FileHandle(arg, mode='rb',
-> 1330                               name=name, offset=offset, size=size)
   1331         self.offset_size = None
   1332         self.pages = []

~/miniconda3/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py in __init__(self, file, mode, name, offset, size)
   3517         self._close = True
   3518         self.is_file = False
-> 3519         self.open()
   3520 
   3521     def open(self):

~/miniconda3/lib/python3.7/site-packages/skimage/external/tifffile/tifffile.py in open(self)
   3528             self._file = os.path.realpath(self._file)
   3529             self._dir, self._name = os.path.split(self._file)
-> 3530             self._fh = open(self._file, self._mode)
   3531             self._close = True
   3532             if self._offset is None:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/yuanchen/Projects/ashlar/does-not-exist.tif'
```

**Comment by huanlity** [comment]
Thanks, it was called indeed.

**Comment by Yu-AnChen** [comment]
@jmuhlich Here's the issue

```python
In [9]: skimage.io.imread('/Users/yuanchen/Downloads/Cycle_0_F040.tif').shape                                                                                            
Out[9]: (1, 1, 4, 2048, 2048, 3)
```
And we are currently [parsing the image shape to get tile size and number of channels in ashlar's fileseries reader](https://github.com/labsyspharm/ashlar/blob/2587ea683c924e1b6d3cc4913e17532266471c5d/ashlar/fileseries.py#L86-L93)
```
        self._tile_size = np.array(img.shape[:2])
        self._dtype = img.dtype
        self.multi_channel_tiles = False
        # Handle multi-channel tiles (pattern must not include channel).
        if len(self.channel_map) == 1 and img.ndim == 3:
            self.channel_map = {c: None for c in range(img.shape[2])}
            self.multi_channel_tiles = True
        self._num_channels = len(self.channel_map)
```

@huanlity it looks like there are 3 z-plane images, we are aware that multiple z planes imaging is required by CODEX vendor, do you know whether it's possible to just pick one and writing it into the tiff when converting from ims?

**Comment by Yu-AnChen** [comment]
(when looking at the image closely, I'm not so sure about the 3-z plans, it could be just a tifffile bug. The file size (32 MB) is the right size for a 16-bit 4-channel image of size 2048x2048)

@huanlity a workaround you could do while we upgrade the tifffile version that you could `pip install tifffile` in the ashlar env, scikit-image will use it over the vendored version. 

When running ashlar, do not use the `--pyramid` option neither the `-f crc4.ome.tif`, ashlar will write single-channel mosaics, which can then be combined using the [ome-tiff-pyramid-tools](https://github.com/labsyspharm/ome-tiff-pyramid-tools). Note that you should specify the pixel size when using the `pyramid_assemble.py` script. 

Again, thanks for reporting the issue, we'll work on solving it.

**Comment by jmuhlich** [comment]
@huanlity Thanks for sharing the sample image to help us get to the bottom of this!

**Comment by huanlity** [comment]
Thank you all! All this has been very helpful! I assume `pyramid.tif` in the command below is a ome-tiff, correct?
`python pyramid_assemble.py channel-1.tif channel-2.tif channel-3.tif pyramid.tif --pixel-size 0.65`

**Comment by Yu-AnChen** [comment]
Yes, actually, the command should be 

```python
python pyramid_assemble.py cycle0_channel0.tif cycle0_channel1.tif cycle1_channel0.tif cycle1_channel1.tif crc4-pyramid.ome.tif --pixel-size 0.325
```

Currently the `tile_size` is hardcoded to 1024 [here](https://github.com/labsyspharm/ome-tiff-pyramid-tools/blob/master/pyramid_assemble.py#L135), change it if you need something different.

**Comment by huanlity** [comment]
@Yu-AnChen Thanks for clarifying!

I tried ***.ome.tif and got the error below which I did not get when I used ***.tif.
<img width="1014" alt="ome_tiff_error" src="https://user-images.githubusercontent.com/26349803/124119848-049c1780-da41-11eb-8fa6-93888751d26c.png">

**Comment by huanlity** [comment]
I tried renaming the output file from ***.tif to ***.ome.tif. The file can be viewed in python without problem but cannot be displayed properly in minerva-author. Please see the screenshots below:

displayed in jupyter lab:
![Screen Shot 2021-07-01 at 8 07 23 AM](https://user-images.githubusercontent.com/26349803/124121935-7d03d800-da43-11eb-9536-3d3bc61fe677.png)


displayed in minerva-author:
<img width="1409" alt="Screen Shot 2021-07-01 at 8 08 00 AM" src="https://user-images.githubusercontent.com/26349803/124121946-812ff580-da43-11eb-9c33-ed883373d75e.png">

**Comment by Yu-AnChen** [comment]
@thejohnhoffer Could you help on the Minerva Author side. @jmuhlich and I are looking into the file suffix error in newer version of `tifffile`. Thanks!

**Comment by thejohnhoffer** [comment]
Hi @Yu-AnChen – sure I’ll take a look at this today. Is there a sample image I could take a look at with this problem?

**Comment by huanlity** [comment]
Thanks @Yu-AnChen .

@thejohnhoffer I am sharing a file `crc4.tif` with your hms email via google drive (uploading right now, will take another 5min).

It was generated by this command:

`python ../pyramid_assemble.py cycle_0_channel_0.tif cycle_0_channel_1.tif cycle_0_channel_2.tif cycle_0_channel_3.tif cycle_1_channel_0.tif cycle_1_channel_1.tif cycle_1_channel_2.tif cycle_1_channel_3.tif registration/crc4.tif --pixel-size 0.325`

**Comment by thejohnhoffer** [comment]
Hi @huanlity,

Could you please confirm for me the version of Minerva Author that you are using, and on which OS? After renaming the image to crc4.ome.tif, I was able to seemingly load the image in Minerva Author v1.8.0, as shown below. I will keep searching to identify the source of the behavior you have observed.

![Screenshot from 2021-07-01 15-17-26](https://user-images.githubusercontent.com/9781588/124180710-97a97180-da82-11eb-9f5b-3c8b6d0e1fd4.png)

**Comment by huanlity** [comment]
@thejohnhoffer That is great news! I am using minerva on one of the google compute engine VM I created. I cloned the latest version I believe.
I will create a fresh env to try again. Thanks!

**Comment by thejohnhoffer** [comment]
@huanlity if you are running minerva author from source, I would recommend checking out the latest stable version. The master branch is at the moment a work in progress and currently seems to give a different error for crc4.ome.tif,

**Comment by thejohnhoffer** [comment]
From within the Minerva Author project directory, checkout the latest stable release:
```git checkout tags/v1.8.0 -b v1.8.0-branch```
Please let me know if you still run into issues.

**Comment by huanlity** [comment]
@thejohnhoffer The stable version works great! Thank you so much!
<img width="1311" alt="Screen Shot 2021-07-01 at 4 07 39 PM" src="https://user-images.githubusercontent.com/26349803/124183622-7cd8fc00-da86-11eb-869a-7e0904e35c53.png">

**Comment by huanlity** [comment]
Great, I think we have temporally resolved this issue by:
1. Running stitching and registration together without the for loop.
2. Creating pyramid separately using [ome-tiff-pyramid-tools](https://github.com/labsyspharm/ome-tiff-pyramid-tools).
3. Using scikit-image vendored version of `tifffile` instead of the stand-alone `tifffile` package.
4. Using a stable version of minerva-author release for proper visualization and renaming ***.tif to ***.ome.tif before loading to minerva.

@ArtemSokolov @jmuhlich @Yu-AnChen @thejohnhoffer 
Thank you everybody for your input, time, and patience.

Huan Wang
