### ISSUE TITLE
Setup Coreograph fails on o2

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#29]
Error executing process > 'setup_coreograph'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: error: Job not submitted: please specify runtime limit with -t.
  sbatch: error: Batch job submission failed: Requested time limit is invalid (missing or exceeds some limit)

Work dir:
  /home/ds230/work/ea/6778ca725d1ae97c7b59b421138d8e

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by ArtemSokolov** [comment]
Make sure you're on a compute (not login) node. The command to run is
`nextflow run labsyspharm/mcmicro-nf/setup.nf --platform O2`

Note that you don't need to install tools on O2. I keep up-to-date versions of all modules in `/n/groups/lsp/mcmicro`. This is where the O2 config will look for them:
https://github.com/labsyspharm/mcmicro-nf/blob/13cf7860e278d5214e78f0d5e6d1edc22a1caaf8/nextflow.config#L17

If you do end up installing tools somewhere else, you will need to overwrite the config location with `--tools path/to/your/own/tools` for all `-profile O2` runs.

**Comment by ArtemSokolov** [comment]
Can you let me know which setup command you tried that produced a failure?

**Comment by DenisSch** [comment]
This issue is gone.
