### ISSUE TITLE
Question on adding Mesmer as one of the segmentation options

### ISSUE THREAD

**Issue by huanlity** [labsyspharm/mcmicro#306]
Github issue is probably not the ideal place to raise this but I know you guys are monitoring this repo so here am I.

I heard from my manager that MCMICRO has the plan to include mesmer as one of the segmentation methods in the MCMICRO pipeline. Can you guys provide an update on the timeline and status if you don't mind? Thanks!

**Comment by ArtemSokolov** [comment]
We reached out to the developers of Mesmer, who already have a Docker container with the method. There is a couple of issues, described in 
https://github.com/vanvalenlab/deepcell-applications/issues/12
and
https://github.com/vanvalenlab/deepcell-applications/issues/13
that need to be resolved, before the container can be plugged into MCMICRO.

There is no specific timeline, but the developers of Mesmer encourage contributions from the community. If you want to submit a pull request addressing one or both of the above issues, we can help test the new container in the context of MCMICRO.

No problem to ask questions in GitHub issues, but we also monitor the `mcmicro` tag on https://forum.image.sc/, which may be more appropriate for longer conversations.

**Comment by ArtemSokolov** [comment]
Mesmer has been added in #321 
Currently, it can be run alongside other segmentation methods via `--probability-maps`:

```
nextflow run labsyspharm/mcmicro --in exemplar-001 --probability-maps unmicst,ilastik,mesmer
```
