### ISSUE TITLE
Proposed changes to docs

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#322]
1. Add a new FAQ describing `-profile singularity`
2. Create a new `Changes Log` section. Move `Roadmap` to be a subsection under the new Changes section. Rename `Roadmap` to `Modules`.
3. Move `Nextflow Workflow/Parameter Reference` to be a subsection under `Parameter Tuning`
4. ~Replace video thumbnails with video embedding (or at least, add a "play" graphic on top of the thumbnails to indicate that the thumbnails are clickable.)~
5. Add a separate tab for a) showing how to cite MCMICRO, b) listing publications that use MCMICRO. Add a "How do I cite?" section to the FAQ that will point to the new tab.
6. ~Parameter Tuning > S3Segmenter: several places use incorrectly capitalized `S3seg-opts`. Modify all of them to be lowercase `s3seg-opts`.~
7. Add a note about Docker Desktop having a 2GB memory limit by default. Suggest that users increase this value after installing Docker.
8. Move `module load java` up higher in https://mcmicro.org/documentation/run-O2.html, since Java is required for `nextflow run labsyspharm/mcmicro/setup/O2ext.nf` in Step 2.

**Comment by clarenceyapp** [comment]
@Yu-AnChen has #4 done in one of his forks.

**Comment by ArtemSokolov** [comment]
Addressed in #371 and #374
