### ISSUE TITLE
Error during cellstates step on exemplar data 001

### ISSUE THREAD

**Issue by MargotCh** [labsyspharm/mcmicro#334]
Hi, 
I was trying to process exemplar-001 data from your website but the pipeline ran into an error during the cellstates:worker process. This is the error I got:
```
Error executing process > 'cellstates:worker (scimap-1)'

Caused by:
  Process `cellstates:worker (scimap-1)` terminated with an error exit status (125)

Command executed:

  scimap-mcmicro -o .  unmicst-exemplar-001_cell.csv

Command exit status:
  125

Command output:
  (empty)

Command error:
  Unable to find image 'labsyspharm/scimap:0.17.7' locally
  docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io: No address associated with hostname.
  See 'docker run --help'.

```
I'm working on an Ubuntu version 20.04.1 LTS with 64 bit. 

Do you know what could be the problem?

**Comment by ArtemSokolov** [comment]
Hi @MargotCh,

Looks like a hiccup with Docker. Can you try the following command?

`docker pull labsyspharm/scimap:0.17.7`

If it succeeds, you should be able to restart the pipeline (use `-resume` to continue where it left off).

If the command fails, then something is wrong with your Docker installation.

**Comment by MargotCh** [comment]
That worked, thank you!
