### ISSUE TITLE
Does mcmicro support registration of brightfield whole slide images sequentially stained?

### ISSUE THREAD

**Issue by kaizen89** [labsyspharm/mcmicro#338]
Hi,
I was wondering whether `mcmicro` allows the registration /alignment of WSI brightfield images of the same slide that was stained/ de-stained and re-stained repetitively for one marker at a time?
Thank you

**Comment by jmuhlich** [comment]
Not directly, since mcmicro uses ashlar for stitching and ashlar doesn't support that (see labsyspharm/ashlar#99). However if you can find a separate solution for registration, you can use the resulting registered whole-slide image as input to the segmentation and quantification steps in mcmicro.

**Comment by ArtemSokolov** [comment]
@kaizen89 Did you get your question answered in https://github.com/labsyspharm/ashlar/issues/99 ?

If you have pre-stitched images, place them in the `myproject/registration` folder, then tell the pipeline to proceed with probability map generation:

```
nextflow run labsyspharm/mcmicro --in myproject/ --start-at probability-maps
```


I'm going to close this issue, but please feel free to re-open if you have more follow-up.
