### ISSUE TITLE
ValueError: Label and intensity image shapes must match, except for channel (last) axis.

### ISSUE THREAD

**Issue by huanlity** [labsyspharm/mcmicro#341]
I am having this error at the quantification step during a MCMICRO pipeline run for a CyCIF data sample. I did not get this error for the example dataset: exemplar-001 though. I also checked the shape of the label image and the intensity image, whose x and y are the same as shown at the bottom. Do you have any idea? Thanks!

`ValueError: Label and intensity image shapes must match, except for channel (last) axis.
`

More details:

`Command executed:

  python /app/CommandSingleCellExtraction.py --image unmicst-cycif_tma_010.ome.tif     --masks cell*.tif --output . --channel_names markers.csv

Command exit status:
  1

Command output:
  {'masks': ['cell.ome.tif'], 'image': 'unmicst-cycif_tma_010.ome.tif', 'channel_names': 'markers.csv', 'output': '.', 'intensity_props': {'mean_intensity'}, 'mask_props': None}
  Extracting single-cell data for unmicst-cycif_tma_010.ome.tif...
  Finished 0
  Finished 1
  Finished 2
  Finished 3
  Finished 4
  Finished 5
  Finished 6
  Finished 7
  Finished 8
  Finished 9
  Finished 10
  Finished 11
  Finished 12
  Finished 13
  Finished 14
  Finished 15
  Finished 16
  Finished 17
  Finished 18
  Finished 19
  Finished 20
  Finished 21
  Finished 22
  Finished 23
  Finished 24
  Finished 25
  Finished 26
  Finished 27
  Finished 28
  Finished 29
  Finished 30
  Finished 31
  Finished 32
  Finished 33
  Finished 34
  Finished 35
  Finished 36
  Finished 37
  Finished 38
  Finished 39
  Finished 40
  Finished 41
  Finished 42
  Finished 43

Command error:
  Traceback (most recent call last):
    File "/app/CommandSingleCellExtraction.py", line 11, in <module>
      SingleCellDataExtraction.MultiExtractSingleCells(**args)
    File "/app/SingleCellDataExtraction.py", line 265, in MultiExtractSingleCells
      ExtractSingleCells(masks,image,channel_names,output, mask_props=mask_props, intensity_props=intensity_props)
    File "/app/SingleCellDataExtraction.py", line 242, in ExtractSingleCells
      scdata_z = MaskZstack(masks_loaded,image,channel_names_loaded_checked, mask_props=mask_props, intensity_props=intensity_props)
    File "/app/SingleCellDataExtraction.py", line 137, in MaskZstack
      MaskChannel(masks_loaded[mask_names[nm]],image_loaded_z, intensity_props=intensity_props)
    File "/app/SingleCellDataExtraction.py", line 34, in MaskChannel
      dat = measure.regionprops_table(
    File "/usr/local/lib/python3.9/site-packages/skimage/measure/_regionprops.py", line 840, in regionprops_table
      regions = regionprops(label_image, intensity_image=intensity_image,
    File "/usr/local/lib/python3.9/site-packages/skimage/measure/_regionprops.py", line 1155, in regionprops
      props = RegionProperties(sl, label, label_image, intensity_image,
    File "/usr/local/lib/python3.9/site-packages/skimage/measure/_regionprops.py", line 217, in __init__
      raise ValueError('Label and intensity image shapes must match,'
  ValueError: Label and intensity image shapes must match, except for channel (last) axis.`

![Screen Shot 2022-01-04 at 9 04 53 PM](https://user-images.githubusercontent.com/26349803/148149185-cf7de8ea-89fb-46f1-89ed-66f31ebe0b3b.png)

**Comment by clarenceyapp** [comment]
Hi @huanlity can you please confirm how many rows and markers you have in your .csv file? Are there 44 markers or more? Thanks.

**Comment by huanlity** [comment]
@clarenceyapp It is 44, same as the number of channels.

**Comment by ArtemSokolov** [comment]
@huanlity Does your `markers.csv` have a single column AND a header? For legacy reasons, the quantification module will accept a file listing one marker name per line. So it would incorrectly interpret the header as one of the markers in a single-column .csv.

In other words, this is a valid `markers.csv` with four markers:
```
channel,marker_name
1,DNA
2,CD45
3,CD3
4,CD4
```

and this is another valid `markers.csv` with four markers:
```
DNA
CD45
CD3
CD4
```
(which is supported for backwards compatibility)

However, this file would be interpreted as having five markers:
```
marker_name
DNA
CD45
CD3
CD4
```
and would cause a mismatch in the number of channels during quantification.

I think we can probably adjust how the quantification module parses `markers.csv` and remove `marker_name` from the list of markers, if it appears as the first line in a single-column file.
