### ISSUE TITLE
Problem with dearray on big image

### ISSUE THREAD

**Issue by MargotCh** [labsyspharm/mcmicro#343]
Hey,

I'm analyzing a 100 core TMA imaged by RareCyte Orion platform and when trying to use MCMICRO Coreograph terminates with an error. Analyzing a smaller portion of the image with only four cores works but anything bigger than that gives the same error. 

My code and the error: 
`nextflow run labsyspharm/mcmicro --in Documents/CLL_Core1/TMA_Full --tma --start-at dearray --stop-at quantification --core-opts '--channel 1' --unmicst-opts '--channel 2' --s3seg-opts '--probMapChan 2'
`

`N E X T F L O W  ~  version 21.04.3
Launching `labsyspharm/mcmicro` [ecstatic_stonebraker] - revision: 2abf17eaca [master]
executor >  local (1)
[-        ] process > illumination           -
[-        ] process > registration:ashlar    -
[da/00a859] process > dearray:coreograph (1) [  0%] 0 of 1
[-        ] process > segmentation:worker    -
[-        ] process > segmentation:s3seg     -
[-        ] process > quantification:mcquant -
[-        ] process > cellstates:worker      -
executor >  local (1)
[-        ] process > illumination           -
[-        ] process > registration:ashlar    -
[da/00a859] process > dearray:coreograph (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > segmentation:worker    -
[-        ] process > segmentation:s3seg     -
[-        ] process > quantification:mcquant -
[-        ] process > cellstates:worker      -
Error executing process > 'dearray:coreograph (1)'

Caused by:
  Process `dearray:coreograph (1)` terminated with an error exit status (1)

Command executed:

  python /app/UNetCoreograph.py --channel 1      --imagePath Full_Core.ome.tiff --outputPath .

Command exit status:
  1

Command output:
  WARNING! IF USING FOR TISSUE SPLITTING, IT IS ADVISED TO SET --downsampleFactor TO HIGHER THAN DEFAULT OF 5

Command error:
  /usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
    warn("The default mode, 'constant', will be changed to 'reflect' in "
  /usr/local/lib/python3.6/dist-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
    warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
  Traceback (most recent call last):
    File "/app/UNetCoreograph.py", line 650, in <module>
      outputChan = [0, numChan-1]
  TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
`

Do you have suggestions on what I could try to fix it? I'd be happy to help setting up new modules to get through this problem.

**Comment by clarenceyapp** [comment]
Hi @MargotCh 
At the time of Coreograph's development, it wasn't possible to explicitly extract the total number of channels to loop over, so we inferred that number by counting how many planes it took before we encountered the next resolution pyramid in the ome.tif stack. Assuming your image is a multiresolution pyramid, then there may be something about the metadata that we have not encountered before. There is a more formal solution that I can deploy this week. I guess the file is too big to send over and test on it, so I suggest I make the changes and you can test it after it is ready.

Where was the image stitched? On the Orion or elsewhere?

Clarence

**Comment by DenisSch** [comment]
Thank you @clarenceyapp 
The image was stitched on the Orion and is indeed too large to share. Please let us know what we can do to help with the fix.

**Comment by clarenceyapp** [comment]
resolved this by making the channel number identification code more robust. Coreograph release 2.2.8.
