### ISSUE TITLE
add auto-threshold module

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/mcmicro#351]
Add a module with the auto-threshold code from https://github.com/jmuhlich/auto-minerva/blob/main/story.py#L12-L39 that just emits the model parameters for use by other modules. Cellcutter can use the results to reject background tiles, visualization modules can use them to set scaling parameters for rendering, etc.

**Comment by clarenceyapp** [comment]
It could be useful to replace S3segmenter's Otsu implementation with this so that no background cells get picked up in the first place and go on to quantification, cellcutter, etc.
https://github.com/HMS-IDAC/S3segmenter/blob/c536958585d6c5cefca2dd6561d5b39524de0699/S3segmenter.py#L493
