### ISSUE TITLE
[s3seg] ValueError: Integers to negative integer powers are not allowed.

### ISSUE THREAD

**Issue by Mr-Milk** [labsyspharm/mcmicro#357]
When I run s3seg, one image raises the following errors and others pass all the analysis.

The image to replicate the issue, [download](https://uofmacau-my.sharepoint.com/:i:/g/personal/yb97643_umac_mo/EW3NmxukS9tNr2pP377olQIB3sQ2rBqG5WKQ5gnePJ2TtA?e=lA4Ngs)

```
Error executing process > 'segmentation:s3seg (1)'

Caused by:
  Process `segmentation:s3seg (1)` terminated with an error exit status (1)

Command executed:

  python /app/S3segmenter.py         --imagePath 15.ome.tiff --stackProbPath 15_Probabilities_8.tif         --nucleiRegion localThreshold --logSigma 3 30 --segmentCytoplasm segmentCytoplasm --cytoMethod ring --cytoDilation 3 --outputPath .

Command exit status:
  1

Command output:
  Using first channel by default!

Command error:
  /usr/local/lib/python3.7/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
    warn("The default mode, 'constant', will be changed to 'reflect' in "
  /usr/local/lib/python3.7/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
    warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
  Traceback (most recent call last):
    File "/app/S3segmenter.py", line 536, in <module>
      exportMasks(nucleiMaskTemp,nucleiCrop,outputPath,filePrefix,'nuclei',commit,metadata,args.saveFig,args.saveMask)
    File "/app/S3segmenter.py", line 335, in exportMasks
      **metadata_args
    File "/app/save_tifffile_pyramid.py", line 76, in save_pyramid
      np.array(img_shape[1:]) / (2**subifds) / 16
  ValueError: Integers to negative integer powers are not allowed.
```

The command I used to run the pipeline, i put the image in the `test/registration` folder
```
nextflow run labsyspharm/mcmicro \
	--in test \
	--start-at probability-maps \
	--unmicst-opts '--tool unmcist-solo --channel 8 --scalingFactor 1.54 --mean 0.0005 --std 0.0005' \
	--s3seg-opts '--nucleiRegion localThreshold --logSigma 3 30 --segmentCytoplasm segmentCytoplasm --cytoMethod ring --cytoDilation 3' \
	-profile standard,GPU
```

**Comment by ArtemSokolov** [comment]
Hi @Mr-Milk,

I believe that means that watershed didn't find any cells. (@clarenceyapp please correct me if I'm wrong.) Updating it to a more informative message has been on our list for a while (#244).

One thing I notice is that you are computing your probability maps using channel 8, but segment with watershed on channel 1 (the default). Can you try adding `--probMapChan 8` to your `--s3seg-opts`? (See the bottom of Scenario 1 in https://mcmicro.org/tuning/s3seg.html for more information.)

Keeping the two modules in sync with a single `--channel` parameter has also been on our list for a bit (#317). I will try and implement it over the next few weeks.

**Comment by clarenceyapp** [comment]
@Mr-Milk can you send us the .ome.tiff and the probability map from UnMICST? I'll investigate on my side.
It's a different error message if there are no cells. Also, using the same channel between UnMICST and S3segmenter does help with accuracy but shouldn't break it if you don't. 

Clarence

**Comment by Mr-Milk** [comment]
@ArtemSokolov Here is the preview of the image, can be confirmed by eyes that there are cells. Is it possible that the `--logSigma 3 30` filter out all the cells? I also tried adding `--probMapChan 8` but got the same error message.

<img width="167" alt="image" src="https://user-images.githubusercontent.com/23433306/155052104-e0a1aff8-a2bf-436b-8689-ec15573ae9fe.png">

@clarenceyapp Here is the link to the two file 
- pmap: [link](https://uofmacau-my.sharepoint.com/:i:/g/personal/yb97643_umac_mo/EbI2V3hm2wlBqPt_jUfJMREB-aVEQ8f3y9IOt9_VpJTngQ?e=Pap3R5) 
- origin `.ome.tiff`: [link](https://uofmacau-my.sharepoint.com/:i:/g/personal/yb97643_umac_mo/EW3NmxukS9tNr2pP377olQIBZ4ndBmn_AafuqA0IFIfyRw?e=e2Yhwq)

**Comment by clarenceyapp** [comment]
Hi @Mr-Milk ,
The code that handles writing output files in s3seg assumes that the image is at least 1024x1024 pixels so that it can form a multiresolution pyramid file. We haven't encountered an image of smaller size, so we will need to relax this limit. Do you have larger images that you can test in the meantime?

The `logSigma` range of 3-30 should be fine since most of your cells appear to be about 7-10 pixels in diameter. The `probMapChan` parameter of 8 or even 9 will be important since that channel is used to filter out false positive cells.

**Comment by clarenceyapp** [comment]
https://github.com/HMS-IDAC/S3segmenter/blob/c536958585d6c5cefca2dd6561d5b39524de0699/save_tifffile_pyramid.py#L72

**Comment by ArtemSokolov** [comment]
@clarenceyapp Based on the original post, it seems that all the other images work fine.

Would it make sense for us to NOT construct a pyramid for images smaller than 1024x1024?

**Comment by clarenceyapp** [comment]
Yes, that's what I proposed.

**Comment by Mr-Milk** [comment]
Yes, most of my other images are ~650\*650 and they all pass the run, but this one is the smallest with 229\*354. Don't know if this is related? 

Sorry, I don't have a large enough image on my hand for testing.

**Comment by clarenceyapp** [comment]
@Mr-Milk we just updated s3segmenter to handle smaller images (thanks to @Yu-AnChen). Can you pull the latest version and give it a try? Thanks.

**Comment by Mr-Milk** [comment]
Yeah, it worked! Thanks for the help!
