### ISSUE TITLE
Issues with installing MCMICRO tools on Galaxy 

### ISSUE THREAD

**Issue by vytnav** [labsyspharm/mcmicro#359]
Dear MCMICRO developer, thank you for creating this versatile tool!
However, I have issues with installing some of the MCMICRO tools on Galaxy (ASHLAR, UnMICST, Coreograph, BaSiC). After installation the packages that are used by these tools are unresolved, so when a tool is run, required libraries are missing which results in an error. Maybe you have any ideas what could be the underlying problem?  Interestingly, S3segmenter and quantification seems to be installed correctly.

**Comment by luke-c-sargent** [comment]
hello! it appears as though you are using conda dependency resolution for these tools. a few clarifying questions:
- did you get the tools from the galaxy toolshed or did you install them yourself from another source?
- are there any particular libraries causing the error commonly or error output you could share?

**Comment by vytnav** [comment]
Thanks for the quick reply! All the tools are from Galaxy Toolshed.
Looks like the installation process fails to install some or all libraries and actually it gets stuck at Installing tool dependencies phase.
here is the example of the error from installing Coreograph. Please find the long LOG below:
galaxy.queue_worker INFO 2022-02-23 10:26:56,637 [pN:main,p:12455,tN:Thread-1] Instance 'main' received 'reload_toolbox' task, executing now.
galaxy.queue_worker DEBUG 2022-02-23 10:26:56,638 [pN:main,p:12455,tN:Thread-1] Executing toolbox reload on 'main'
galaxy.util WARNING 2022-02-23 10:26:56,638 [pN:main,p:12455,tN:Thread-1] directory not found: /home/vytnav/galaxy/lib/galaxy/util/../../../config/plugins/activities
galaxy.tool_util.toolbox.base INFO 2022-02-23 10:26:56,639 [pN:main,p:12455,tN:Thread-1] Parsing the tool configuration /home/vytnav/galaxy/lib/galaxy/config/sample/tool_conf.xml.sample
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,639 [pN:main,p:12455,tN:Thread-1] Tool path for tool configuration /home/vytnav/galaxy/lib/galaxy/config/sample/tool_conf.xml.sample is None
galaxy.tool_util.toolbox.base ERROR 2022-02-23 10:26:56,642 [pN:main,p:12455,tN:Thread-1] ("Error reading tool configuration file from path '%s': %s", 'evolution/codingSnps.xml', "[Errno 2] No such file or directory: '/home/vytnav/galaxy/tool-data/codingSnps.loc'")
galaxy.tool_util.toolbox.base ERROR 2022-02-23 10:26:56,643 [pN:main,p:12455,tN:Thread-1] ("Error reading tool configuration file from path '%s': %s", 'evolution/add_scores.xml', "[Errno 2] No such file or directory: '/home/vytnav/galaxy/tool-data/add_scores.loc'")
galaxy.tool_util.toolbox.base ERROR 2022-02-23 10:26:56,643 [pN:main,p:12455,tN:Thread-1] ("Error reading tool configuration file from path '%s': %s", 'phenotype_association/sift.xml', "[Errno 2] No such file or directory: '/home/vytnav/galaxy/tool-data/sift_db.loc'")
galaxy.tool_util.toolbox.base INFO 2022-02-23 10:26:56,644 [pN:main,p:12455,tN:Thread-1] Parsing the tool configuration /home/vytnav/galaxy/config/shed_tool_conf.xml
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,644 [pN:main,p:12455,tN:Thread-1] Tool path for shed tool configuration /home/vytnav/galaxy/config/shed_tool_conf.xml is /home/vytnav/galaxy/database/shed_tools
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,644 [pN:main,p:12455,tN:Thread-1] Reading tools from config files finished (5.633 ms)
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,645 [pN:main,p:12455,tN:Thread-1] Loading section: Get Data
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,645 [pN:main,p:12455,tN:Thread-1] Loading section: Send Data
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,645 [pN:main,p:12455,tN:Thread-1] Loading section: Collection Operations
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,645 [pN:main,p:12455,tN:Thread-1] Loading section: Expression Tools
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,645 [pN:main,p:12455,tN:Thread-1] Loading section: Lift-Over
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,645 [pN:main,p:12455,tN:Thread-1] Loading section: Text Manipulation
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,645 [pN:main,p:12455,tN:Thread-1] Loading section: Convert Formats
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,646 [pN:main,p:12455,tN:Thread-1] Loading section: Filter and Sort
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,646 [pN:main,p:12455,tN:Thread-1] Loaded label: GFF
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,646 [pN:main,p:12455,tN:Thread-1] Loading section: Join, Subtract and Group
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,646 [pN:main,p:12455,tN:Thread-1] Loading section: Fetch Alignments/Sequences
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,646 [pN:main,p:12455,tN:Thread-1] Loading section: Operate on Genomic Intervals
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,646 [pN:main,p:12455,tN:Thread-1] Loading section: Statistics
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,646 [pN:main,p:12455,tN:Thread-1] Loading section: Graph/Display Data
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,646 [pN:main,p:12455,tN:Thread-1] Loading section: Phenotype Association
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,646 [pN:main,p:12455,tN:Thread-1] Loading section: MCMICRO
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,646 [pN:main,p:12455,tN:Thread-1] Loading section: TEST
galaxy.tool_util.toolbox.base DEBUG 2022-02-23 10:26:56,647 [pN:main,p:12455,tN:Thread-1] Loading tool panel finished (2.354 ms)
galaxy.tool_util.toolbox.views.edam DEBUG 2022-02-23 10:26:56,675 [pN:main,p:12455,tN:Thread-1] Loading EDAM tool panel finished (2.048 ms)
galaxy.tool_util.toolbox.views.edam DEBUG 2022-02-23 10:26:56,677 [pN:main,p:12455,tN:Thread-1] Loading EDAM tool panel finished (1.874 ms)
galaxy.tool_util.toolbox.integrated_panel DEBUG 2022-02-23 10:26:56,677 [pN:main,p:12455,tN:Thread-1] Writing integrated tool panel config file to '/home/vytnav/galaxy/config/integrated_tool_panel.xml'
galaxy.datatypes.registry DEBUG 2022-02-23 10:26:56,680 [pN:main,p:12455,tN:Thread-1] Loaded external metadata tool: __SET_METADATA__
galaxy.tools.special_tools DEBUG 2022-02-23 10:26:56,680 [pN:main,p:12455,tN:Thread-1] Loaded history export tool: __EXPORT_HISTORY__
galaxy.tools.special_tools DEBUG 2022-02-23 10:26:56,682 [pN:main,p:12455,tN:Thread-1] Loaded history export to uri tool: __EXPORT_HISTORY_TO_URI__
galaxy.tools.special_tools DEBUG 2022-02-23 10:26:56,682 [pN:main,p:12455,tN:Thread-1] Loaded history import tool: __IMPORT_HISTORY__
galaxy.tools.special_tools DEBUG 2022-02-23 10:26:56,683 [pN:main,p:12455,tN:Thread-1] Loaded data fetch tool: __DATA_FETCH__
galaxy.queue_worker INFO 2022-02-23 10:26:56,683 [pN:main,p:12455,tN:Thread-1] Queuing async task rebuild_toolbox_search_index for main.
galaxy.queue_worker DEBUG 2022-02-23 10:26:56,691 [pN:main,p:12455,tN:Thread-1] Toolbox reload (53.725 ms)
galaxy.queue_worker INFO 2022-02-23 10:26:56,706 [pN:main,p:12455,tN:Thread-1] Instance 'main' received 'rebuild_toolbox_search_index' task, executing now.
galaxy.tools.search DEBUG 2022-02-23 10:26:56,706 [pN:main,p:12455,tN:Thread-1] Starting to build toolbox index of panel default.
galaxy.tools.search DEBUG 2022-02-23 10:26:56,713 [pN:main,p:12455,tN:Thread-1] Toolbox index of panel default finished (6.690 ms)
galaxy.tools.search DEBUG 2022-02-23 10:26:56,713 [pN:main,p:12455,tN:Thread-1] Starting to build toolbox index of panel ontology:edam_operations.
galaxy.config DEBUG 2022-02-23 10:26:56,714 [pN:main,p:12455,tN:AnyIO worker thread] Finished waiting for toolbox reload (1603.131 ms)
galaxy.tools.search DEBUG 2022-02-23 10:26:56,721 [pN:main,p:12455,tN:Thread-1] Toolbox index of panel ontology:edam_operations finished (7.818 ms)
galaxy.tools.search DEBUG 2022-02-23 10:26:56,721 [pN:main,p:12455,tN:Thread-1] Starting to build toolbox index of panel ontology:edam_topics.
galaxy.tool_util.deps.conda_util DEBUG 2022-02-23 10:26:56,729 [pN:main,p:12455,tN:AnyIO worker thread] Executing command: /home/vytnav/galaxy/database/dependencies/_conda/bin/conda create -y --quiet --override-channels --channel conda-forge --channel bioconda --channel defaults --name mulled-v1-0d274b3fe53404e1d7a2a2a9adde45e5b6e94d5703c3fc0fc71173cc0499310f python=3.6 tensorflow-estimator=1.15.1 tensorflow=1.15 cython scikit-image=0.14.2 matplotlib tifffile=2020.2.16 scipy=1.1.0 opencv pytiff=0.8.1
galaxy.tools.search DEBUG 2022-02-23 10:26:56,737 [pN:main,p:12455,tN:Thread-1] Toolbox index of panel ontology:edam_topics finished (15.906 ms)
127.0.0.1 - - [23/Feb/2022:10:26:56 +0200] "GET /api/tool_shed_repositories?name=s3segmenter&owner=perssond HTTP/1.1" 200 - "http://localhost:8080/admin/toolshed" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0"

**Comment by luke-c-sargent** [comment]
hello!

sorry for the delay, i have been trying to replicate your issue and it led to some rabbit-hole delving. roughly, we've switched focus to containerization with the tools, and so that's currently the best way to run them. indeed, the decision to lean in to docker was in part driven by conda dependency resolution headaches like the above. we still want to maintain conda support (with tool wrappers designed to support any use case) but if using dockerized tools is an option for you, that's probably the fastest, most consistently stable way.

if that works for you, i am happy to help getting your local instance set up to use docker (by modifying your job_conf.xml file; more info can be seen in `<galaxy dir>/config/job_conf.xml.sample_advanced`, and further reading is here: https://docs.galaxyproject.org/en/release_20.09/admin/jobs.html)

**Comment by ArtemSokolov** [comment]
Hi @vytnav,

I hope you were able to get the tools working. I am going to close this issue due to inactivity. However, feel free to reopen if you would like to follow up.
