### ISSUE TITLE
Auto-Minerva unable to process Coreograph output

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#398]
Presently, Auto-Minerva expects a pyramid OME-TIFF, while Coreograph produces flat `.tif` files.

To fix:
**Option 1:** Allow Auto-Minerva to process small pyramid-free images, such as the ones produced by Coreograph
**Option 2:** Update Coreograph to produce pyramid OME-TIFF files

**Comment by hengkp** [comment]
Hi @ArtemSokolov,

I came from the [#72187](https://forum.image.sc/t/error-in-unmicst-segmentation-process/72187) After run this command:

`nextflow run labsyspharm/mcmicro --in /sisplockers/MCMICRO/exemplar-002 --viz --segmentation ilastik`

It shows an error as you have mentioned as follows:

> N E X T F L O W  ~  version 22.04.5
> Launching `https://github.com/labsyspharm/mcmicro` [exotic_wozniak] DSL2 - revision: 1472f63a5c [master]
> executor >  local (22)
> [-        ] process > illumination                   -
> [12/457d92] process > registration:ashlar            [100%] 1 of 1 ✔
> [c1/d41aa8] process > dearray:coreograph (1)         [100%] 1 of 1 ✔
> [-        ] process > segmentation:roadie:runTask    -
> executor >  local (22)
> [-        ] process > illumination                   -
> [12/457d92] process > registration:ashlar            [100%] 1 of 1 ✔
> [c1/d41aa8] process > dearray:coreograph (1)         [100%] 1 of 1 ✔
> [-        ] process > segmentation:roadie:runTask    -
> [a7/d06a56] process > segmentation:worker (ilasti... [100%] 4 of 4 ✔
> [0e/67b4ff] process > segmentation:s3seg (2)         [100%] 4 of 4 ✔
> [6d/e5dd52] process > quantification:mcquant (3)     [  0%] 0 of 1
> [-        ] process > downstream:worker              -
> [c5/a08e0a] process > viz:roadie:runTask (1)         [100%] 3 of 3
> [e6/ad177e] process > viz:autominerva (1)            [ 33%] 1 of 3, failed: 1
> [1d/81d04b] process > provenance                     [100%] 1 of 1 ✔
> Error executing process > 'viz:autominerva (1)'
> 
> Caused by:
>   Process `viz:autominerva (1)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   python /app/minerva-author/src/save_exhibit_pyramid.py 3.tif 3.json 3
> 
> Command exit status:
>   1
> 
> Command output:
>   (empty)
> 
> Command error:
>   Traceback (most recent call last):
>     File "/app/minerva-author/src/save_exhibit_pyramid.py", line 209, in <module>
>       main(ome_tiff, author_json, output_dir, root_url, vis_dir, force)
>     File "/app/minerva-author/src/save_exhibit_pyramid.py", line 152, in main
>       exhibit_config = make_exhibit_config(opener, root_url, saved)
>     File "/app/minerva-author/src/save_exhibit_pyramid.py", line 84, in make_exhibit_config
>       (num_channels, num_levels, width, height) = opener.get_shape()
>   TypeError: cannot unpack non-iterable NoneType object
> 
> Work dir:
>   /home/nodeadmin/work/e6/ad177e3a424332735287e818c4c439
> 
> Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

Also, for the log file:

`cat /home/nodeadmin/work/e6/ad177e3a424332735287e818c4c439/.command.log`

> Traceback (most recent call last):
>   File "/app/minerva-author/src/save_exhibit_pyramid.py", line 209, in <module>
>     main(ome_tiff, author_json, output_dir, root_url, vis_dir, force)
>   File "/app/minerva-author/src/save_exhibit_pyramid.py", line 152, in main
>     exhibit_config = make_exhibit_config(opener, root_url, saved)
>   File "/app/minerva-author/src/save_exhibit_pyramid.py", line 84, in make_exhibit_config
>     (num_channels, num_levels, width, height) = opener.get_shape()
> TypeError: cannot unpack non-iterable NoneType object

I see you suggest two options, but I am unsure how to perform them. Please advice.

Thanks,
Heng

**Comment by ArtemSokolov** [comment]
Hi Heng,

Just a small update:

* We have been able to reproduce your issue with UnMicst in another environment and are in the process of debugging now.
* The two options are proposals for future development. After some discussion, we are going to pursue option 2 and will try to implement a solution soon.

Best,
-Artem
