### ISSUE TITLE
example output of mcmicro

### ISSUE THREAD

**Issue by giovp** [labsyspharm/mcmicro#470]
Hi,

I was wondering if there is an example dataset that corresponds to the output of mcmicro. I was able to find the input datasets in the website (and the very useful output specs) but I'm interested in the output of the pipeline: is there any download available?

Thanks in advance,
Giovanni

**Comment by ArtemSokolov** [comment]
Hi @giovp,

Yes, you can get the output of a fully processed `exemplar-001` from GitHub Actions, which runs our automated tests.
Take a look at https://github.com/labsyspharm/mcmicro/actions/runs/3568191059
If you scroll down to the "Artifacts" section at the bottom of the page, you can click on "exemplar-001" in that section to download a .zip file with all outputs.

Best,
-Artem

**Comment by giovp** [comment]
this is fantastic, I managed to download and use the files. Thanks a lot!
