### ISSUE TITLE
Standard pipeline for cell type annotation based on spatial feature table 

### ISSUE THREAD

**Issue by JiayuanDing100** [labsyspharm/mcmicro#493]
Hi,

This is great work! Thanks for your contributions in this field.

I am new to mIF data analysis. I am wondering whether there is an existing standard pipeline for cell type annotation and neighboring analysis after we get Spatial Feature Map from mIF data, like how to infer the label of each cell based on spatial table.

Thanks,

**Comment by ArtemSokolov** [comment]
Hi @JiayuanDing100,

Thanks for the kind words! Cell type assignment is usually a semi-manual process and requires some information about marker genes. There are several toolboxes that aim to guide users through the process. Take a look at

https://scimap.xyz/tutorials/2-scimap-tutorial-cell-phenotyping/
https://squidpy.readthedocs.io/en/stable/external_tutorials/tutorial_vizgen_mouse_liver.html#Assign-Cell-Types

-Artem

**Comment by JiayuanDing100** [comment]
@ArtemSokolov Thanks for the quick response!

For single cell data with thousands of genes, it is true to annotate cell types for each cell based on marker genes.
I am wondering whether it is true for MCMICRO output ?  since our data only has around 28 protein markers.

Thanks,

**Comment by ArtemSokolov** [comment]
That should still be possible, especially for immune cell subpopulations.

The canonical approach (and the one taken by the above toolboxes) is to cluster the single-cell feature tables and then annotate individual clusters based on known marker <-> cell type associations. (For example, a cluster with high CD45, high CD3 and high CD8 would correspond to cytotoxic T cells).

**Comment by JiayuanDing100** [comment]
Sounds great! Really appreciate your help! Nice work!!!
