### ISSUE TITLE
Ashlar stitch and register error

### ISSUE THREAD

**Issue by ShihongWu** [labsyspharm/mcmicro#519]
Hi MCMICRO team

I'm trying to use ASHLAR to stitch and merge my whole-slide images generated by CellDIVE.
The structure of my files looks like this
--raw
   --S001_bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5
       --bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_cy3.tif
       --bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_cy5.tif
       --bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_dapi.tif
       --bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_fitc.tif
       --bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P001_Z01_cy3.tif
       --bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P001_Z01_cy5.tif
       --bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P001_Z01_dapi.tif
       --bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P001_Z01_fitc.tif
       -- ...
   --S002_DAPI_dapi_aSMA_fitc_TNC_cy3_PNAd_cy5
   --S003_bleach_dapi_bleach_fitc_bleach_cy3_bleach_cy5
   --S004_DAPI_dapi_HLA_DR_fitc_FN_cy3_PDPN_cy5
   --...

S001 stands for cycle 1. P000 stands for position 0. cy3, cy5, dpi, fitc, stand for different channels here. 

The params.yml looks like this:
workflow:
  single-formats: .tif
  start-at: registration
  stop-at: background
  background: true 

My markers.csv looks like this:
channel_number,cycle_number,marker_name,Filter,excitation_wavelength,emission_wavelength,background,exposure,remove
1,1,DNA_1,DAPI,395,431,,35,TRUE
2,1,AF488_background,FITC,485,525,,100,TRUE
3,1,AF555_background,Cy3,555,590,,200,TRUE
4,1,AF647_background,Cy5,640,690,,500,TRUE
5,2,DNA_2,DAPI,395,431,,35,
6,2,aSMA,FITC,485,525,AF488_background,800,
7,2,TNC,Cy3,555,590,AF555_background,300,
8,2,PNAd,Cy5,640,690,AF647_background,300,
9,3,DNA_3,DAPI,395,431,,35,TRUE
10,3,AF488_bleach_1,FITC,485,525,,100,TRUE
11,3,AF555_bleach_1,Cy3,555,590,,200,TRUE
12,3,AF647_bleach_1,Cy5,640,690,,500,TRUE
13,4,DNA_4,DAPI,395,431,,35,
14,4,HLA_DR,FITC,485,525,AF488_bleach_1,1500,
15,4,FN,Cy3,555,590,AF555_bleach_1,200,
16,4,PDPN,Cy5,640,690,AF647_bleach_1,1500,
17,5,DNA_5,DAPI,395,431,,35,TRUE
18,5,AF488_bleach_2,FITC,485,525,,100,TRUE
19,5,AF555_bleach_2,Cy3,555,590,,200,TRUE
20,5,AF647_bleach_2,Cy5,640,690,,500,TRUE
21,6,DNA_6,DAPI,395,431,,35,
22,6,CLU,FITC,485,525,AF488_bleach_2,1200,
23,6,PDGFRa,Cy3,555,590,AF555_bleach_2,1200,
24,6,CD31,Cy5,640,690,AF647_bleach_2,450,
25,7,DNA_7,DAPI,395,431,,35,TRUE
26,7,AF488_bleach_3,FITC,485,525,,100,TRUE
27,7,AF555_bleach_3,Cy3,555,590,,200,TRUE
28,7,AF647_bleach_3,Cy5,640,690,,500,TRUE
29,8,DNA_8,DAPI,395,431,,35,
30,8,COL3,FITC,485,525,AF488_bleach_3,1500,
31,8,MMP9,Cy3,555,590,AF555_bleach_3,800,
32,8,VIM,Cy5,640,690,AF647_bleach_3,600,
33,9,DNA_9,DAPI,395,431,,35,TRUE
34,9,AF488_bleach_4,FITC,485,525,,100,TRUE
35,9,AF555_bleach_4,Cy3,555,590,,200,TRUE
36,9,AF647_bleach_4,Cy5,640,690,,500,TRUE
37,10,DNA_10,DAPI,395,431,,35,
38,10,COL1A1,FITC,485,525,AF488_bleach_4,1500,
39,10,SPP1,Cy3,555,590,AF555_bleach_4,1500,
40,10,DNA_11,DAPI,395,431,,35,TRUE
41,11,AF488_bleach_5,FITC,485,525,,100,TRUE
42,11,AF555_bleach_5,Cy3,555,590,,200,TRUE
43,11,AF647_bleach_5,Cy5,640,690,,500,TRUE
44,12,DNA_12,DAPI,395,431,,35,
45,12,PCK,FITC,485,525,AF488_bleach_5,1500,
46,12,FAP,Cy3,555,590,AF555_bleach_5,1500,
47,12,CD45,Cy5,640,690,AF647_bleach_5,1000,

When I ran MCMICRO, I got this error:

ERROR ~ Error executing process > 'registration:ashlar'

Caused by:
  Process `registration:ashlar` terminated with an error exit status (139)

Command executed:

  ashlar 'bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_cy3.tif' 'bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_cy5.tif' .......'dapi_dapi_PCK_fitc_FAP_cy3_CD45_cy5_45041_19_4AIP_1_S012_P999_Z01_cy3.tif' 'dapi_dapi_PCK_fitc_FAP_cy3_CD45_cy5_45041_19_4AIP_1_S012_P999_Z01_cy5.tif' 'dapi_dapi_PCK_fitc_FAP_cy3_CD45_cy5_45041_19_4AIP_1_S012_P999_Z01_dapi.tif' 'dapi_dapi_PCK_fitc_FAP_cy3_CD45_cy5_45041_19_4AIP_1_S012_P999_Z01_fitc.tif'  -m 30  -o for_mcmicro.ome.tif
Command exit status:
  139

Command output:
  (empty)

Work dir:
  /gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/work/46/3962322e5f7d7af0825e43159d1303

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run

 -- Check '.nextflow.log' file for details

I was wondering if I need to add more arguments to specify the input files.
Thanks a lot for your time and assistance!

**Comment by ArtemSokolov** [comment]
Hi @ShihongWu,

Exit status 139 often indicates an out-of-memory event. Can you share what the log file `/gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/work/46/3962322e5f7d7af0825e43159d1303/.command.log` looks like?

-Artem

**Comment by ShihongWu** [comment]
Hi Artem,

I just checked the log file /gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/work/46/3962322e5f7d7af0825e43159d1303/.command.log, there is nothing inside, it's just empty. But under the directory /gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/work/46/3962322e5f7d7af0825e43159d1303, there are .command.run, .command.sh, and .command.begin. 
The .command.run is listed below:
[tma392@rescomp1 3962322e5f7d7af0825e43159d1303]$ cat .command.run
#!/bin/bash
# NEXTFLOW TASK: registration:ashlar
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

# aws cli retry config
export AWS_RETRY_MODE=standard 
export AWS_MAX_ATTEMPTS=5
# aws helper
nxf_s3_upload() {
    local name=$1
    local s3path=$2
    if [[ "$name" == - ]]; then
      aws s3 cp --only-show-errors --storage-class STANDARD - "$s3path"
    elif [[ -d "$name" ]]; then
      aws s3 cp --only-show-errors --recursive --storage-class STANDARD "$name" "$s3path/$name"
    else
      aws s3 cp --only-show-errors --storage-class STANDARD "$name" "$s3path/$name"
    fi
}

nxf_s3_download() {
    local source=$1
    local target=$2
    local file_name=$(basename $1)
    local is_dir=$(aws s3 ls $source | grep -F "PRE ${file_name}/" -c)
    if [[ $is_dir == 1 ]]; then
        aws s3 cp --only-show-errors --recursive "$source" "$target"
    else 
        aws s3 cp --only-show-errors "$source" "$target"
    fi
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/work/46/3962322e5f7d7af0825e43159d1303/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    sync || true
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    set +u; env - PATH="$PATH" ${TMP:+SINGULARITYENV_TMP="$TMP"} ${TMPDIR:+SINGULARITYENV_TMPDIR="$TMPDIR"} singularity exec --pid -B /gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro -C -H "$PWD" -B /gpfs3/well/immune-rep/users/tma392/mcmicro/images:/mounted_images /gpfs3/well/immune-rep/users/tma392/mcmicro/images/labsyspharm-ashlar-1.17.0.img /bin/bash -ue /gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/work/46/3962322e5f7d7af0825e43159d1303/.command.sh
}

nxf_stage() {
    true
    # stage input files
    ln -s /gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/raw/S001_bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5/bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_cy3.tif bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_cy3.tif
......
ln -s /gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/raw/S012_dapi_dapi_PCK_fitc_FAP_cy3_CD45_cy5/dapi_dapi_PCK_fitc_FAP_cy3_CD45_cy5_45041_19_4AIP_1_S012_P999_Z01_fitc.tif dapi_dapi_PCK_fitc_FAP_cy3_CD45_cy5_45041_19_4AIP_1_S012_P999_Z01_fitc.tif
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/work/46/3962322e5f7d7af0825e43159d1303/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    nxf_stage

    set +e
    ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY

the .command.sh looks like:
[tma392@rescomp1 3962322e5f7d7af0825e43159d1303]$ cat .command.sh
#!/bin/bash -ue
ashlar 'bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_cy3.tif' 'bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_cy5.tif' 'bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_dapi.tif' 'bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P000_Z01_fitc.tif'
......
'dapi_dapi_PCK_fitc_FAP_cy3_CD45_cy5_45041_19_4AIP_1_S012_P999_Z01_cy3.tif' 'dapi_dapi_PCK_fitc_FAP_cy3_CD45_cy5_45041_19_4AIP_1_S012_P999_Z01_cy5.tif' 'dapi_dapi_PCK_fitc_FAP_cy3_CD45_cy5_45041_19_4AIP_1_S012_P999_Z01_dapi.tif' 'dapi_dapi_PCK_fitc_FAP_cy3_CD45_cy5_45041_19_4AIP_1_S012_P999_Z01_fitc.tif'  -m 30  -o for_mcmicro.ome.tif

Hope these are helpful.

Thanks a lot!

**Comment by ArtemSokolov** [comment]
Hm. If the `.command.log` is empty, that probably means that the tool never even started running. I see that you have a lot of AWS-specific code in `.command.run`. Are you running the pipeline on AWS? If so, were you able to run exemplar-001 from the tutorial successfully?

If you are having the same issue with exemplar-001, then the issue is likely with the AWS config. One way to debug it is to run `source .command.run` directly and see what errors it produces. Common problems include not setting credentials as environmental variables and not having proper IAM permissions (https://nextflow.io/docs/latest/aws.html#amazon-cloud).

**Comment by ShihongWu** [comment]
Hi Artem,

I'm running this pipeline on our cluster. I just checked and I'm able to run exemplar-001 from registration to downstream analysis. 

These are the codes that I use ran exemplar-001:
srun -p short --cpus-per-task 5 --pty bash 
module load Nextflow/23.04.2
nextflow run labsyspharm/mcmicro \
--in /gpfs3/well/immune-rep/users/tma392/mcmicro/exemplar-001 \
-profile singularity \
-c /gpfs3/well/immune-rep/users/tma392/mcmicro/custom.config

the config looks like:
singularity {
    enabled = true
    autoMounts = true
    cacheDir  = '/gpfs3/well/immune-rep/users/tma392/mcmicro/images'
    runOptions = '-C -H "$PWD" -B /gpfs3/well/immune-rep/users/tma392/mcmicro/images:/mounted_images'
}

and the output is like this:
N E X T F L O W  ~  version 23.04.2
Launching `https://github.com/labsyspharm/mcmicro` [pedantic_goldberg] DSL2 - revision: 5eac7773d7 [master]
executor >  local (4)
[-        ] process > illumination                   -
[53/7ba447] process > registration:ashlar            [100%] 1 of 1 ✔
[-        ] process > background:backsub             -
[-        ] process > dearray:coreograph             -
[-        ] process > dearray:roadie:runTask         -
[-        ] process > segmentation:roadie:runTask    -
[c9/01cda3] process > segmentation:worker (mesmer-1) [100%] 1 of 1 ✔
[-        ] process > segmentation:s3seg             -
[61/757ca1] process > quantification:mcquant (1)     [100%] 1 of 1 ✔
[73/affa5b] process > downstream:worker (scanpy-1)   [100%] 1 of 1 ✔
[-        ] process > viz:autominerva                -
Completed at: 25-Sep-2023 11:48:10
Duration    : 2m 55s
CPU hours   : (a few seconds)
Succeeded   : 4


These are the codes I use to run my own data:
srun -p short --cpus-per-task 10 --pty bash 
module load Nextflow/23.04.2
nextflow run labsyspharm/mcmicro \
--in /gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro \
-profile singularity \
-c /gpfs3/well/immune-rep/users/tma392/mcmicro/custom.config

same config here.

I was wondering if it's because of the format of my image files. Cause they're not ome.tiff files and the nomenclature is quite complicated. My files are quite large too, for every channel, it has about 2700 moves. Every cycle has 4 channels.
Hope these info are helpful!

Thanks a lot for your time and assistance!

**Comment by jmuhlich** [comment]
Sorry, that kind of image format is not currently supported by mcmicro -- it requires formats that BioFormats can perceive as a single image set. You would need to run ashlar manually using the `fileseries` reader which is somewhat documented at this image.sc thread https://forum.image.sc/t/ashlar-how-to-pass-multiple-images-to-be-stitched/49864/4, then place the stitched image in your mcmicro `registration/` folder and run mcmicro with `--start-at segmentation`.

**Comment by ShihongWu** [comment]
> Sorry, that kind of image format is not currently supported by mcmicro -- it requires formats that BioFormats can perceive as a single image set. You would need to run ashlar manually using the `fileseries` reader which is somewhat documented at this image.sc thread https://forum.image.sc/t/ashlar-how-to-pass-multiple-images-to-be-stitched/49864/4, then place the stitched image in your mcmicro `registration/` folder and run mcmicro with `--start-at segmentation`.

Hi Jeremy, thanks for your help! I tried to run ashlar manually using the fileseries reader as you suggested.
These are the command lines that I used to run this:

python -m venv ashlar-skylake
source ashlar-skylake/bin/activate
pip install ashlar
ashlar "fileseries|/gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/raw/S001_bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5|pattern=bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_{series:4}_Z01_(\w+).tif"

Then I got this error:
Traceback (most recent call last):
  File "/gpfs3/well/immune-rep/users/tma392/python/ashlar-skylake/lib/python3.10/site-packages/jnius/env.py", line 347, in get_jdk_home
    jdk_home = realpath(
  File "/apps/eb/2020b/skylake/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/posixpath.py", line 394, in realpath
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs3/well/immune-rep/users/tma392/python/ashlar-skylake/bin/ashlar", line 33, in <module>
    sys.exit(load_entry_point('ashlar==1.17.0', 'console_scripts', 'ashlar')())
  File "/gpfs3/well/immune-rep/users/tma392/python/ashlar-skylake/bin/ashlar", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/apps/eb/2020b/skylake/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/apps/eb/2020b/skylake/software/Python/3.10.4-GCCcore-11.3.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/gpfs3/well/immune-rep/users/tma392/python/ashlar-skylake/lib/python3.10/site-packages/ashlar/scripts/ashlar.py", line 8, in <module>
    from .. import reg
  File "/gpfs3/well/immune-rep/users/tma392/python/ashlar-skylake/lib/python3.10/site-packages/ashlar/reg.py", line 39, in <module>
    import jnius
  File "/gpfs3/well/immune-rep/users/tma392/python/ashlar-skylake/lib/python3.10/site-packages/jnius/__init__.py", line 45, in <module>
    from .reflect import *  # noqa
  File "/gpfs3/well/immune-rep/users/tma392/python/ashlar-skylake/lib/python3.10/site-packages/jnius/reflect.py", line 19, in <module>
    class Class(JavaClass, metaclass=MetaJavaClass):
  File "jnius/jnius_export_class.pxi", line 118, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 178, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 95, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 54, in jnius.create_jnienv
  File "/gpfs3/well/immune-rep/users/tma392/python/ashlar-skylake/lib/python3.10/site-packages/jnius/env.py", line 60, in get_java_setup
    JAVA_HOME = get_jdk_home(platform)
  File "/gpfs3/well/immune-rep/users/tma392/python/ashlar-skylake/lib/python3.10/site-packages/jnius/env.py", line 351, in get_jdk_home
    raise Exception('Unable to find javac')
Exception: Unable to find javac

Could you help me with this? Many thanks!

**Comment by jmuhlich** [comment]
You need to have a java JDK installed for bioformats to work. Ashlar loads bioformats (and thus java) even if you are using the fileseries reader with plain tiffs, unfortunately. A quick way to test whether your JDK is installed properly for ashlar is with this command:

```python -c 'import jnius'```

If you see the error "Unable to find javac", it's not working yet. If you see no output, then it _is_ working and you can try your ashlar command again.

**Comment by jmuhlich** [comment]
The `{series}` string must only match the numeric part of the position number. Also you need to include `{channel}` in your pattern to tell ashlar which component of the filenames encodes the channel identifier. Your pattern should look like this, I think:

```bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_P{series}_Z01_{channel}.tif```

If the `{series}` and `{channel}` components are bounded by a fixed string (like in your filenames) then you don't need to include the length.

**Comment by ArtemSokolov** [comment]
One alternative to installing dependencies is to run the ASHLAR container.

* Look inside your container cache directory (`/gpfs3/well/immune-rep/users/tma392/mcmicro/images`) for the name of the ashlar container. Should look something like `labsyspharm-ashlar-1.17.0.sif`.
* Start up the container interactively with:

`singularity shell -C -H "$PWD" -B /gpfs3/well/immune-rep/users/tma392/mcmicro/images:/mounted_images labsyspharm-ashlar-1.17.0.sif` (Replace `labsyspharm-ashlar-1.17.0.sif` with the name found in the first step. Here, I am using the options from your `custom.config` to make your images visible inside the container under `/mounted_images`.)

* Once inside the container, verify that ASHLAR is available with `ashlar --help` and that your images are visible in `/mounted_images`.
* Run the fileseries command. Make sure the output is written back to `/mounted_images`, so that it's persistent once the container is terminated.

**Comment by ShihongWu** [comment]
> singularity shell -C -H "$PWD" -B /gpfs3/well/immune-rep/users/tma392/mcmicro/images:/mounted_images

Hi Artem,

Thank you for your suggestion. I did what you suggested and ran into another error.

singularity shell -C -H "$PWD" -B /gpfs3/well/immune-rep/users/tma392/mcmicro/images:/mounted_images labsyspharm-ashlar-1.17.0.img
Apptainer> ashlar "fileseries|/gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/raw/S001_bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5|pattern=bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_{series}_Z01_{channel}.tif|overlap=0.1"

the output is:
Stitching and registering input images
Cycle 0:
    reading fileseries|/gpfs3/well/immune-rep/users/tma392/mcmicro/45041_19_4AIP_1/for_mcmicro/raw/S001_bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5|pattern=bkgnd_dapi_bkgnd_fitc_bkgnd_cy3_bkgnd_cy5_45041_19_4AIP_1_S001_{series}_Z01_{channel}.tif|overlap=0.1
Traceback (most recent call last):
  File "/usr/local/bin/ashlar", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 212, in main
    return process_single(
  File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 237, in process_single
    reader = build_reader(filepaths[0], plate_well=plate_well)
  File "/usr/local/lib/python3.10/dist-packages/ashlar/scripts/ashlar.py", line 358, in build_reader
    reader = reader_class(path, **kwargs)
TypeError: FileSeriesReader.__init__() missing 2 required positional arguments: 'width' and 'height'

The problem here is my images are irregular, so I can't provide the 'width' and 'height' here.
But "ASHLAR allows reconstruction of irregular and discontinuous sample edges, as is often seen in biological slide samples." Is there any way to walk around it? Thanks!

**Comment by ShihongWu** [comment]
> python -c 'import jnius'

Hi Jeremy, thanks a lot for helping me here. 
I tried python -c 'import jnius', the return is like this: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'jnius'

I also checked java on the cluster using java -version, the return is:
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (build 1.8.0_382-b05)
OpenJDK 64-Bit Server VM (build 25.382-b05, mixed mode)

Hope these are helpful! Many thanks!

**Comment by ShihongWu** [comment]
Hi both, thanks for your time and assistance! Much appreciated! I found that I have a metadata that contains the row, column, x and y position info of all the tiles/moves. I was wondering if this info helps.

here's part of the metadata file:

```
<pixel_moves>
<image_path>H:\Cell_DIVE_ScansH\45041_19_4AIP_1\scanplan\scanplan.tif</image_path>
<image_base_mag>10.000000</image_base_mag>
<objective_mag>20.000000</objective_mag>
<canvas_xform exists="1" a="192.307693" b="0.000000" c="0.000000" d="192.307693" du="127.500000" dv="127.500000"/>
<cam img_size_x="2040.000000" img_size_y="2040.000000" pixel_size_x="6.500000" pixel_size_y="6.500000"/>
<roi_count>1</roi_count>
<roi id="0" type="region">
	<label>region_001</label>
	<overlap x="0.100000" y="0.100000"/>
	<roi_rect x="11.068200" y="1.583400" width="35.360001" height="22.547199" cen_x="28.748199" cen_y="12.856999"/>
	<moves>
		<move id="0" enabled="0" row="0" col="0" xp="2319" yp="495" xs="11.399700" ys="1.914900"/>
		<move id="1" enabled="0" row="0" col="1" xp="2434" yp="495" xs="11.996400" ys="1.914900"/>
		<move id="2" enabled="0" row="0" col="2" xp="2549" yp="495" xs="12.593100" ys="1.914900"/>
		<move id="3" enabled="0" row="0" col="3" xp="2664" yp="495" xs="13.189799" ys="1.914900"/>
		<move id="4" enabled="0" row="0" col="4" xp="2778" yp="495" xs="13.786499" ys="1.914900"/>
		<move id="5" enabled="0" row="0" col="5" xp="2893" yp="495" xs="14.383199" ys="1.914900"/>
		<move id="6" enabled="0" row="0" col="6" xp="3008" yp="495" xs="14.979898" ys="1.914900"/>
		<move id="7" enabled="0" row="0" col="7" xp="3122" yp="495" xs="15.576598" ys="1.914900"/>
		<move id="8" enabled="0" row="0" col="8" xp="3237" yp="495" xs="16.173298" ys="1.914900"/>
		<move id="9" enabled="0" row="0" col="9" xp="3352" yp="495" xs="16.769999" ys="1.914900"/>
		<move id="10" enabled="0" row="0" col="10" xp="3467" yp="495" xs="17.366699" ys="1.914900"/
```

**Comment by jmuhlich** [comment]
Sorry, I didn't realize you have an irregular grid. "Out of the box" ashlar only supports this for Bioformats-supported formats which include stage position metadata. See the list here: https://bio-formats.readthedocs.io/en/stable/supported-formats.html . What is the file extension of the CellDive metadata file? There is a small chance it's in this list already.

If Bioformats doesn't support this format directly, you have two options:

1. Create an OME-XML "companion" file that references all of your tiffs with their stage position and pixel size metadata extracted from the CellDive metadata file. OME-XML is an open standard that's supported by Bioformats, so you can read the specification and create your own OME-XML with the necessary metadata. There is some example code for a different metadata format here that you can adapt: https://forum.image.sc/t/microscope-image-stitching-in-python/75871/11

2. Create custom subclasses of the Ashlar Reader and Metadata classes that can read the CellDive metadata file and tiff naming convention directly. This is probably more work and does require reasonable Python programming skills, but is more robust in the long term. You can use the Zeiss Zen reader as a starting point: https://github.com/labsyspharm/ashlar/blob/master/ashlar/zen.py

If you want to pursue this then please open an issue in the Ashlar repository for further discussion, as we are getting outside the scope of mcmicro here - https://github.com/labsyspharm/ashlar/issues

**Comment by ShihongWu** [comment]
> Sorry, I didn't realize you have an irregular grid. "Out of the box" ashlar only supports this for Bioformats-supported formats which include stage position metadata. See the list here: https://bio-formats.readthedocs.io/en/stable/supported-formats.html . What is the file extension of the CellDive metadata file? There is a small chance it's in this list already.
> 
> If Bioformats doesn't support this format directly, you have two options:
> 
> 1. Create an OME-XML "companion" file that references all of your tiffs with their stage position and pixel size metadata extracted from the CellDive metadata file. OME-XML is an open standard that's supported by Bioformats, so you can read the specification and create your own OME-XML with the necessary metadata. There is some example code for a different metadata format here that you can adapt: https://forum.image.sc/t/microscope-image-stitching-in-python/75871/11
> 2. Create custom subclasses of the Ashlar Reader and Metadata classes that can read the CellDive metadata file and tiff naming convention directly. This is probably more work and does require reasonable Python programming skills, but is more robust in the long term. You can use the Zeiss Zen reader as a starting point: https://github.com/labsyspharm/ashlar/blob/master/ashlar/zen.py
> 
> If you want to pursue this then please open an issue in the Ashlar repository for further discussion, as we are getting outside the scope of mcmicro here - https://github.com/labsyspharm/ashlar/issues

Hi Jeremy, thank you! The file extension of the CellDive metadata file is xml. I'll try your suggestions! I'd like to pursue this but I don't know how to move this discussion to Ashlar repository. Or I should just start a new discussion there?

**Comment by jmuhlich** [comment]
Ah yes, please start a new issue there to discuss how we can load the CellDive xml file. :)
