### ISSUE TITLE
Exemplar-001 nuclei segmentation is identical to the cell segmentation

### ISSUE THREAD

**Issue by LucaMarconato** [labsyspharm/mcmicro#531]
It appears that the nuclei segmentation in exemplar-001 is incorrect as it coincides with the cell segmentation (see screenshot from FIJI).

<img width="1699" alt="Screenshot 2024-01-06 at 14 06 33" src="https://github.com/labsyspharm/mcmicro/assets/2664412/45cce9fd-b156-4567-9ed0-d205b7ade386">

The two files are located in `exemplar-001/segmentation/unmicst-exemplar_001/` and have filenames `cell.ome.tif` and `nuclei.ome.tif`.

CC @keller-mark, who originally reported the bug in https://github.com/scverse/spatialdata-notebooks/issues/52.

**Comment by LucaMarconato** [comment]
I see a similar problem also with exemplar-002, in fact the segmentation files in `qc/s3seg/unmicst-1/` for cells and nuclei (`cellOutlines.ome.tif` and `nucleiOutlines.ome.tif`), show the same segmentation.

<img width="2056" alt="Screenshot 2024-01-06 at 15 11 08" src="https://github.com/labsyspharm/mcmicro/assets/2664412/ed19b741-4406-4a6a-98c1-6e4ab5d01dc7">

**Comment by ArtemSokolov** [comment]
Thanks, @LucaMarconato. Is this with default parameters?

@clarenceyapp Can you take a look when you have a chance?

**Comment by LucaMarconato** [comment]
The files have been generated by @melonora; can you please comment on this?

**Comment by clarenceyapp** [comment]
By default, cytoplasm segmentation is switched off. So only nuclei are segmented. Users have historically wanted a mask called cell to always get written out even if it's drawing intensities from the nucleus so both files (nucleus and cell) will be duplicates. To get a true cell, cytoplasm, and nucleus mask, the segment cytoplasm flag must be on.

Clarence
________________________________

**Comment by LucaMarconato** [comment]
Thank you for the clarification @clarenceyapp!
