### ISSUE TITLE
Cell segmentation is incorrect on Immunohistochemical staining picture

### ISSUE THREAD

**Issue by egg124** [labsyspharm/mcmicro#543]
It appears that  the cell segmentation is incorrect(see screenshot from FIJI).I input a Immunohistochemical staining picture and the cell segmentation result looks like something went wrong.
![1](https://github.com/labsyspharm/mcmicro/assets/33061182/673e185b-52a1-4cb2-a8d6-0a86365b0d2f)
![2](https://github.com/labsyspharm/mcmicro/assets/33061182/b74b74b4-f16e-4d4e-bc5f-9bea270a2aa1)
![3](https://github.com/labsyspharm/mcmicro/assets/33061182/398a6a07-0be1-4203-96f6-1d01907f5529)

**Comment by egg124** [comment]
This is my params.yml file
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>The MCMICRO params.yml file<<<<<<<<<<<<<<<<<<<<<<<<<<<<
workflow:
  start-at: segmentation
modules:
  watershed:
    version: 1.5.4-large
options:
  mcquant: --masks nucleiRing.ome.tif

**Comment by clarenceyapp** [comment]
@egg124 The input nuclei image needs to resemble a fluorescence image of nuclei such as Hoechst or DAPI as bright pixels on a dark background. In your image, there appears to be regions of cytoplasm as well, which you would need to suppress before feeding into most segmentation tools. Is your input image an RGB image of color dyes? I suggest running color deconvolution in FIJI to separate the nuclei as much as possible from background, resave as 16-bit image, and try rerunning ONLY the segmentation on this new image first. Once you have verified the mask looks better, run quantification on your color-deconvolved image to completion.

**Comment by egg124** [comment]
Thanks for your answering, It really helps me a lot!!!
