### ISSUE TITLE
MCMICRO from dearrayed cores

### ISSUE THREAD

**Issue by josenimo** [labsyspharm/mcmicro#551]
Dear @Yu-AnChen,

I am trying to run MCMICRO from post-dearrayed TMA cores, the images were taken per core, and a WSI never existed. Therefore I have no masks for each core. Which seems to be a problem, the error that gets reported back is:
```No TMA masks in /fast/AG_Coscia/Jose/P18_TNBC/P18_E06_SL574//dearray/masks```
is there a way to bypass this need? 

Thank you for the help

**Comment by ArtemSokolov** [comment]
Hi @josenimo,

Are your dearrayed images in standalone files?
If so, you can just put them all in the `registration/` subfolder and run the pipeline with `tma: false` (i.e., as if they are individual images) to process each core in parallel.

**Comment by josenimo** [comment]
Hey @ArtemSokolov,
Thank you, I got caught up in the specifics, and forgot this could be done.
