### ISSUE TITLE
Naivestates-model: Parameter Not Found

### ISSUE THREAD

**Issue by ke2rchan** [labsyspharm/mcmicro#553]
This is my current workflow that i am trying with exemplar-001 image (see below). however, i keep getting the error "unrecognized parameter naivestates-model". how can i navigatethis?

workflow:
start-at: registration
stop-at: downstream
downstream: [scimap, naivestates]
naivestates-model: /path/mct.csv
options:
naivestates: --umap --plots pdf --log no

**Comment by ArtemSokolov** [comment]
Looks like that one didn't make it into the parameter schema. I just added it to the list of recognizable parameters. Can you try running your workflow again?

**Comment by ke2rchan** [comment]
Yes, the parameter is now recognised. Thank you so much for your help!
