### ISSUE TITLE
Cellpose: Which version is incorporated?

### ISSUE THREAD

**Issue by ke2rchan** [labsyspharm/mcmicro#556]
Hello! I couldn't find any details about which version of Cellpose is used for segmentation by McMicro. Would it be possible to provide me with this information? Any assistance used would be greatly appreciated! :)

**Comment by ArtemSokolov** [comment]
Hi @ke2rchan,

It should be 2.1.1: https://github.com/labsyspharm/mcmicro/blob/master/config/defaults.yml#L94
