### ISSUE TITLE
Segmentation: worker - failed call to cuInit: UNKNOWN ERROR (34)

### ISSUE THREAD

**Issue by simonchow3** [labsyspharm/mcmicro#569]
Hello!

I have been struggling with this issue for the past few weeks (running mcmicro on local workstation).

![image](https://github.com/user-attachments/assets/a58822b4-0437-4d12-b836-ef24a5b6b2a3)

I'm very new to a lot of this, but it seems like there might be some mismatch or incompatibilities between tensorflow, CUDA or some other related packages, in the nextflow or docker container. I did run some tests with seeing if tensorflow[and-cuda] can detect my GPU both locally and via "docker run --gpus all -it labsyspharm/unmicst:2.7.7 bash" and they both seem to work, so I'm a bit unsure as to where the exact problem lies.

I would greatly appreciate any insight or help, thank you!

**Comment by clarenceyapp** [comment]
Hi Simon,
An error 137 means your workstation has run out of RAM for unmicst to finish. How much RAM does your workstation have? And how many pixels wide and high are your images?

Also, can you confirm what is your image pixel size in microns?

The tensorflow issue is a separate problem but is unlikely stopping unmicst from proceeding. In this case, it is not using your GPU and is defaulting to using CPU so you can expect longer processing times (anywhere between 5 to 10 times longer). Unfortunately, tensorflow compatibility issues are hard to debug. Can you provide more details on your OS and GPU you have?

Clarence
________________________________
From: simonchow3 ***@***.***>
Sent: Wednesday, December 25, 2024 12:16:43 AM
To: labsyspharm/mcmicro ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [labsyspharm/mcmicro] Segmentation: worker - failed call to cuInit: UNKNOWN ERROR (34) (Issue #569)


Hello!

I have been struggling with this issue for the past few weeks (running mcmicro on local workstation).

image.png (view on web)<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_user-2Dattachments_assets_a58822b4-2D0437-2D4d12-2Db836-2Def24a5b6b2a3&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Hv2ImNU5v_QaacHDz01XFRrD_bA8Sg7kSTOh8SrzhDk&m=19wic2Arlgd0eXZFG63vkVFbAh2mlke0lGWkqDoVOwjli6jI8p4--QI8OuL0lRIy&s=NYizDJIVe3QnA0h1KEPSuYOp20z5vBIp2KCqxkXwkzE&e=>

I'm very new to a lot of this, but it seems like there might be some mismatch or incompatibilities between tensorflow, CUDA or some other related packages, in the nextflow or docker container. I did run some tests with seeing if tensorflow[and-cuda] can detect my GPU both locally and via "docker run --gpus all -it labsyspharm/unmicst:2.7.7 bash" and they both seem to work, so I'm a bit unsure as to where the exact problem lies.

I would greatly appreciate any insight or help, thank you!

**Comment by simonchow3** [comment]
Hi Clarence,

Thanks for the fast response!

Workstation has 128 GB total RAM.

Image is 60131 px by 72400 px (W x H)
Image pixel size is 0.1725x0.1725 microns.

The workstation I'm using is Dell Precision 7875 tower
--CPU is AMD Ryzen Threadripper PRO 7945WX 12-cores, 4701 Mhz, 12 cores 24 logical processors
--GPU is NVIDIA RTX 4000 Ada Generation (20GB memory here)

Please let me know if there's other info you need regarding the computer or image structure.\

It might also be worth noting that when I've been running this command the past few weeks, it sometimes runs successfully and sometimes has this error, even on the same image (maybe has something to do with currently available RAM?).

Thanks!
Simon

**Comment by simonchow3** [comment]
I managed to fix the issue by increasing the memory and swap size allocations on the WSL terminal I am running this on.

**Comment by clarenceyapp** [comment]
Hi Simon,
Sorry for the delayed response - the team is away for the holidays and will be back next week. Glad you were able to sort that out, and thanks for the information about your images.

The pixel sizes are actually quite finer than images we are accustomed to, which means your images are quite large relative to biological content. May I ask what your end goal is with these images? Are you wanting to just measure mean intensity of the nucleus? If so, these images could be downsampled alot (we typically acquire images at 0.325 or 0.65 microns per pixel) and this would reduce the amount of RAM needed.

We are working on new segmentation methods that will eventually be able to handle much much larger images once we return from break.

Best,
Clarence


Clarence Yapp,  DPhil (Oxon)
Director of Microscopy & Computer Vision
Laboratory of Systems Pharmacology

Harvard Medical School
200 Longwood Avenue
Boston, MA 02115
***@***.******@***.***>


________________________________

**Comment by simonchow3** [comment]
Sorry for late response Clarence, we are just trying to use these images for cell phenotyping and pathway analyses for various drug RoIs. Excited for the new segmentation updates!

**Comment by clarenceyapp** [comment]
Thanks for your reply, Simon. For cell phenotyping using mean intensities (as you are doing right now), it is acceptable to image at a coarser resolution (or downsample your images). This could save you alot of headache later on and would give you a quicker solution to the bottleneck you are encountering.

Best,
Clarence


Clarence Yapp,  DPhil (Oxon)
Director of Microscopy & Computer Vision
Laboratory of Systems Pharmacology

Harvard Medical School
200 Longwood Avenue
Boston, MA 02115
***@***.******@***.***>


________________________________
