### ISSUE TITLE
Update markers.csv of each exemplar to match real data

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/mcmicro#60]
Real data uses the following `marker.csv` structure:

```
channel_number,cycle_number,marker_name,Filter,excitation_wavelength,emission_wavelength
1,1,DNA_1,DAPI,395,431
2,1,AF488,FITC,485,525
3,1,AF555,Sytox,555,590
4,1,AF647,Cy5,640,690
5,2,DNA_2,DAPI,395,431
6,2,A488 background,FITC,485,525
7,2,A555 background,Sytox,555,590
8,2,A647 background,Cy5,640,690
...
```

Update our exemplars to reflect this. Ensure all tools (e.g., quantification) are able to parse the proper structure correctly.

**Comment by DenisSch** [comment]
@ArtemSokolov Please remove any "spaces" in channel names
```
6,2,A488_background,FITC,485,525
7,2,A555_background,Sytox,555,590
8,2,A647_background,Cy5,640,690
```

**Comment by ArtemSokolov** [comment]
@DenisSch The prototype of the new file can be viewed here:
https://mcmicro.s3.amazonaws.com/exemplars/001/exemplar-001/markers_new.csv

Note that there are no spaces in this prototype.

Let us know when quantification is able to handle this format, and we'll replace existing `markers.csv` with `markers_new.csv`.

**Comment by ArtemSokolov** [comment]
Note to self: Since there is now a header in the file, the number of lines to keep should be augmented by one.

https://github.com/labsyspharm/mcmicro-nf/blob/ca9b65f04971464f1c372fb59f62e56185522c6a/exemplar.nf#L26

**Comment by clarenceyapp** [comment]
@ArtemSokolov @DenisSch if you don't think we should have a header, i can remove it. I'm just following the old template, which did have it.

**Comment by ArtemSokolov** [comment]
The header is no problem for me. I just need to properly account for it in the download script.

**Comment by DenisSch** [comment]
I think the header is important, since I will search for "marker_name".

**Comment by DenisSch** [comment]
New release for quantification requires the full CSV file list
https://github.com/labsyspharm/quantification/releases/tag/1.2.0

**Comment by DenisSch** [comment]
I keep this open until testing and integration into mcmicro-nf

**Comment by DenisSch** [comment]
This done now with 1.2.2.
@ArtemSokolov **Important:** CSV file should be shortened to fit the image in exemplar-001
