### ISSUE TITLE
16bit masks should be 32bit

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#61]
@clarenceyapp Segmentation masks with more than 65535 cells should 32 bit instead of 16bit. This creates the memory issues in #59

**Comment by DenisSch** [comment]
@clarenceyapp Was this addressed and pushed? If yes, I will close this issue.

**Comment by ArtemSokolov** [comment]
My suggestion is to leave this issue open until the new s3segmenter version is formally specified in nextflow.config.

**Comment by DenisSch** [comment]
All looks good even for the largest images with "profile O2large"
```
executor >  slurm (6)
[-        ] process > illumination   -
[-        ] process > ashlar         -
[-        ] process > dearray        -
[21/262e74] process > unmicst        [100%] 2 of 2 ✔
[58/059237] process > s3seg          [100%] 2 of 2 ✔
[2e/fd7bbe] process > quantification [100%] 2 of 2 ✔
Completed at: 03-Apr-2020 20:51:04
Duration    : 8h 34m 12s
CPU hours   : 15.8
Succeeded   : 6
```
