### ISSUE TITLE
Ashlar step needs to check that input image list is not empty

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/mcmicro#63]
If the input directory's `raw_images` subdirectory is empty or non-existent, Ashlar will print its usage instructions and exit with an error code. This does stop the pipeline but the output is not helpful in diagnosing the problem. The desired behavior is to print an error about the missing files so the user can act on it.

**Comment by DenisSch** [comment]
@jmuhlich @ArtemSokolov That raises the question whether we should include some checks before even starting any of the modules? Especially on o2 that would safe time, so we don't have to wait for the nodes to be assigned and then cancelled immediately...

**Comment by ArtemSokolov** [comment]
Yes, makes sense to me.

**Comment by Yu-AnChen** [comment]
The mcmicro-old did [implement some checks](https://github.com/labsyspharm/mcmicro-old/blob/ef2cfb8e4011b1e607410ab756a285b4f6e85457/O2/CyCif_Pipeline_O2.py#L41-L231) before initiating the pipeline, not sure how much of that would fit into the current framework tho.

**Comment by ArtemSokolov** [comment]
Addressed by #75
