### ISSUE TITLE
Coreograph: publish TMA_MAP.tif

### ISSUE THREAD

**Issue by clarenceyapp** [labsyspharm/mcmicro#72]
@ArtemSokolov Coreograph writes a summary and QC file that users need in order to map their cores to their respective locations on the slide. Could you please publish this file so that it goes to a folder somewhere where it would be convenient for the user to find? Maybe even at the end along with the .csv files in the quantification step.

**Comment by ArtemSokolov** [comment]
Should we have a separate `QC/` folder that various modules can publish their QC output to?

**Comment by clarenceyapp** [comment]
I think that's a great idea. Either Summary/ or QC/ or something like that.

**Comment by DenisSch** [comment]
Great idea!
