### ISSUE TITLE
New quantification release 1.1.2

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#77]
@ArtemSokolov 
I have created a new release for quantification which fixes a bug when markers are not unique: https://github.com/labsyspharm/quantification/releases
--> 1.1.2

Should I change the release in the config files or what procedure do you recommend?

**Comment by ArtemSokolov** [comment]
I'm was planning on dealing with versioning tomorrow ( specifically, #66 ). So, I could bump it up for you. After tomorrow, it will be much easier to increase version numbers.

Did you ever get the new `markers.csv` format working for quantification? (#60)

**Comment by DenisSch** [comment]
Good point! I will incorporate that and I will let you know tomorrow.
