### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#8]
N E X T F L O W  ~  version 20.01.0
Pulling ArtemSokolov/mcmicro-nf ...
downloaded from https://github.com/ArtemSokolov/mcmicro-nf.git
Launching `ArtemSokolov/mcmicro-nf` [berserk_snyder] - revision: a6713e1a22 [master]
WARN: There's no process matching config selector: ashlar
WARN: There's no process matching config selector: unmicst
executor >  local (2)
executor >  local (2)
[20/ee31ed] process > setup_coreograph [100%] 1 of 1, failed: 1 ✘
[9b/8e0300] process > setup_unmicst    [100%] 1 of 1 ✔
Error executing process > 'setup_coreograph'

Caused by:
  Process `setup_coreograph` terminated with an error exit status (128)

Command executed:

  git clone https://github.com/HMS-IDAC/Coreograph.git
  cd Coreograph
  git checkout e21b137e9bde2b95f0402836bd9bb2658f436aea
  curl -o TMAsegmentation/model1.mat https://mcmicro.s3.amazonaws.com/models/model1.mat

Command exit status:
  128

Command output:
  (empty)

Command error:
  Cloning into 'Coreograph'...
  Downloading TMAsegmentation/RFmodel.mat (134 MB)
  Error downloading object: TMAsegmentation/RFmodel.mat (e5911ab): Smudge error: Error downloading TMAsegmentation/RFmodel.mat (e5911abc765760ca1041b5da451f54931338100349f86ea031c6815df44ff134): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

  Errors logged to Coreograph/.git/lfs/logs/20200220T154756.166717.log
  Use `git lfs logs last` to view the log.
  error: external filter 'git-lfs filter-process' failed
  fatal: TMAsegmentation/RFmodel.mat: smudge filter lfs failed
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry the checkout with 'git checkout -f HEAD'

Work dir:
  /Users/denis/work/20/ee31ed55a057f689680e69ec8297b4

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by ArtemSokolov** [comment]
Thanks, @DenisSch. Looks like IDAC is over their quota for GitHub LFS.

Let me check with Clarence to see if he wants to mode `RFmodel.mat` to S3.
