### ISSUE TITLE
S3 issue with TNP samples

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#81]
```
aused by:
  Process `s3seg (1)` terminated with an error exit status (139)

Command executed:

  python /n/groups/lsp/mcmicro/2020-04-07/S3segmenter/S3segmenter.py --crop noCrop        --imagePath COL8.ome.tif        --maskPath NO_MASK        --nucleiClassProbPath COL8_NucleiPM_1.tif        --conto
ursClassProbPath COL8_ContoursPM_1.tif                --outputPath .

Command exit status:
  139

Command output:
  (empty)

Command error:
  .command.sh: line 2: 10247 Segmentation fault      python /n/groups/lsp/mcmicro/2020-04-07/S3segmenter/S3segmenter.py --crop noCrop --imagePath COL8.ome.tif --maskPath NO_MASK --nucleiClassProbPath COL8
_NucleiPM_1.tif --contoursClassProbPath COL8_ContoursPM_1.tif --outputPath .

Work dir:
  /n/scratch2/ds230/JL_TNP/work/b2/96cf39f65f069eecd58f75cac66f37
```

**Comment by ArtemSokolov** [comment]
Looks like your text got cut off. There's a `$` at the end of each long line.

**Comment by clarenceyapp** [comment]
Agreed. The path to the contours probability map appears to be missing. Are there any other error messages?

**Comment by DenisSch** [comment]
I just edited the error message

**Comment by clarenceyapp** [comment]
@DenisSch it says '10247 Segmentation fault ' which in this case, segmentation is referring to memory allocation instead of image segmentation. Can you try with the increased RAM to see if that fixes it?

**Comment by DenisSch** [comment]
Thanks! I am testing it now!

**Comment by clarenceyapp** [comment]
@ArtemSokolov @DenisSch version 0.2.2 will fix this issue. The label indices were not matching when using cytoplasm ring, which caused regionprops to use more RAM. When using the cytoplasm channel itself for segmentation, this would have been fine. You can probably scale the RAM requirements down to 128 or even 64GB for the TNP sample. Tested successfully locally on exemplar-001 and one of Ajit's whole tissue samples.
