### ISSUE TITLE
Explicitly note that Docker must be running in the instructions

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#9]
N E X T F L O W  ~  version 20.01.0
Launching `ArtemSokolov/mcmicro-nf` [berserk_mercator] - revision: a6713e1a22 [master]
executor >  local (1)
[90/153df7] process > ashlar  [100%] 1 of 1, failed: 1 ✘
[-        ] process > dearray -
[-        ] process > unmicst -
Error executing process > 'ashlar'

Caused by:
  Process `ashlar` terminated with an error exit status (127)

Command executed:

  ashlar  -m 30 --pyramid --ffp  --dfp  -f stitched.ome.tif

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.run: line 63: docker: command not found

Work dir:
  /Users/denis/work/90/153df76a98a0caaf920e9359baf3d4

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by DenisSch** [comment]
Is this due to the previous installation error?

**Comment by ArtemSokolov** [comment]
No, this is the problem:

> .command.run: line 63: docker: command not found

Do you have Docker installed? Your shell doesn't appear to know where it is.

**Comment by ArtemSokolov** [comment]
TODO: Also add information about increasing Docker memory limit
https://docs.docker.com/docker-for-mac/images/menu/prefs-advanced.png
