### ISSUE TITLE
How to handle multiple segmentations in the csv output?

### ISSUE THREAD

**Issue by DenisSch** [labsyspharm/mcmicro#97]
We are about to enable a second segmentation module. Should we create:
1) Subfolders in the quantification folder
2) Change the name of the csv file according to the used segmentation

Vote:
1) Thumbs Up
2) Thumbs Down

**Comment by ArtemSokolov** [comment]
It's not just quantification, right? We need to subdivide prob_maps and segmentation folders too.

**Comment by DenisSch** [comment]
@ArtemSokolov I think all others will get new folders, since the amount and type of files will change. I was just hoping that we can have csv files with different names instead of same name but different folders. Too dangerous...

**Comment by ArtemSokolov** [comment]
Oh, I see.

**Comment by ArtemSokolov** [comment]
If it helps, Nextflow will be keeping track which segmentation method was run on each file, so it can correctly publish resulting files to the proper subfolder. As a consequence, the method name can be provided to quantification, if you want:

`python CommandSingleCellExtraction.py ... --seg-method ilastik`

**Comment by ArtemSokolov** [comment]
Addressed in #168 by having segmentation prepend the probability map generator name to its output folder, leading to automatic resolution of any potential name collisions in all downstream modules.
